BASEPATH=..\..\..

all: start \
  dll \
  end

!include $(BASEPATH)\OS2MAK.INC

dll: $(CAMLIBS)\gpminolt.dll

.c.o:
   @$(CC) -o $@ $< $(CCFLAGS)

OBJS= util.o \
      info.o \
      data.o \
      packet.o \
      delete.o \
      download.o \
      capture.o \
      status.o \
      dimagev.o \
      upload.o

dimagev.def: dimagev.o
   @$(MAKEDEF)

$(CAMLIBS)\gpminolt.dll: $(OBJS) dimagev.def
   @$(LINK) $(DLLLINKFLAGS) -o $@ $** $(LIBS)
