BASEPATH=..\..

all: start \
  dll \
  end

!include $(BASEPATH)\os2mak.inc

dll: $(CAMLIBS)\gpdscf1.dll

OBJS=sonydscf1.o \
     command.o \
     chotplay.o \
     getuint.o

.c.o:
   @$(CC) -o $@ $< $(CCFLAGS)

sonydscf1.def: sonydscf1.o
   @$(MAKEDEF)

$(CAMLIBS)\gpdscf1.dll: $(OBJS) sonydscf1.def
   $(LINK) $(DLLLINKFLAGS) -o $@ $** $(LIBS)

