# Cirrus CI configuration
# https://cirrus-ci.com/github/gphoto/libgphoto2

task:
  name: FreeBSD
  freebsd_instance:
    matrix:
      image_family: freebsd-14-3

  env:
    # Set to 10 instead of 1 to avoid problems when new commits are submitted
    # during a run.
    CIRRUS_CLONE_DEPTH: 10
    CFLAGS: -Wall -Wextra -O2
    MAKE_FLAGS: -j 2

  pkginstall_script:
    - pkg install -y autoconf automake libtool gettext-tools gettext-runtime pkgconf libltdl libexif libgd libxml2 curl
  configure_script:
    - autoreconf -ivf
    - ./configure --with-camlibs=everything || { tail -300 config.log; false; }
  compile_script:
    - make
  test_script:
    - make check
  install_script:
    - make install
