BASEPATH=..\..

all: start \
  dll \
  end

!include $(BASEPATH)\OS2MAK.INC

dll: ..\gpkonica.dll

OBJS=konica.o \
     lowlevel.o \
     library.o \

.c.o :
   @$(CC) -o $@ $< $(CCFLAGS) -Ic:\xfree86\include\glib12 -IE:\gs\gs6.61\zlib

konica.def: library.o
   $(MAKEDEF)

..\gpkonica.dll:konica.def $(OBJS)
   @$(LINK) $(DLLLINKFLAGS) -o $@ $** $(LIBS) -LC:\XFREE86\LIB -lglib12
