/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"
#include "tree_list_util.h"

GtkWidget *create_main_win(void) {

  GtkWidget *main_win;
  GtkWidget *main_vbox;
  GtkWidget *main_menubar;
  guint tmp_key;
  GtkWidget *file;
  GtkWidget *file_menu;
  GtkAccelGroup *file_menu_accels;
  GtkWidget *exit;
  GtkWidget *edit;
  GtkWidget *select;
  GtkWidget *camera;
  GtkWidget *camera_menu;
  GtkAccelGroup *camera_menu_accels;
  GtkWidget *select_camera;
  GtkWidget *export, *export_menu, *html_export;
  GtkWidget *main_toolbar;
  GtkWidget *tmp_toolbar_icon;
  GtkWidget *button2;
  GtkWidget *button4;
  GtkWidget *button5;
  GtkWidget *hseparator;
  GtkWidget *main_hpaned;
  GtkWidget *main_hbox_hp;
  GtkWidget *main_vpaned;
  GtkWidget *main_vbox_vp;
  GtkWidget *main_scroll_local;
  GtkWidget *main_vp_local;
  GtkWidget *main_tree_local;
  GtkWidget *main_scroll_cam;
  GtkWidget *main_vp_cam;
  GtkWidget *main_tree_hbox;
  GtkWidget *main_tree_cam;
  GtkWidget *main_leaf_cam;
  GtkWidget *main_label;
  GtkWidget *main_hbox_sb;
  GtkWidget *main_statbar;
  GtkWidget *main_progbar;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  main_win = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (main_win, "main_win");
  gtk_object_set_data (GTK_OBJECT (main_win), "main_win", main_win);
  gtk_window_set_title (GTK_WINDOW (main_win), _("gphoto2 - Prototype"));
  gtk_window_set_default_size (GTK_WINDOW (main_win), 750, 450);

  gtk_signal_connect(GTK_OBJECT(main_win), "destroy", 
		     GTK_SIGNAL_FUNC(exit_callback), NULL);

  main_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (main_vbox, "main_vbox");
  gtk_widget_ref (main_vbox);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "main_vbox", main_vbox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (main_vbox);
  gtk_container_add (GTK_CONTAINER (main_win), main_vbox);

  main_menubar = gtk_menu_bar_new ();
  gtk_widget_set_name (main_menubar, "main_menubar");
  gtk_widget_ref (main_menubar);
  gtk_object_set_data_full (GTK_OBJECT(main_win), "main_menubar", 
			    main_menubar, (GtkDestroyNotify)gtk_widget_unref);
  gtk_widget_show (main_menubar);
  gtk_box_pack_start (GTK_BOX (main_vbox), main_menubar, FALSE, FALSE, 0);

  file = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (file)->child),
                                   _("_File"));
  gtk_widget_set_name (file, "file");
  gtk_widget_ref (file);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "file", file,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file);
  gtk_container_add (GTK_CONTAINER (main_menubar), file);

  file_menu = gtk_menu_new ();
  gtk_widget_set_name (file_menu, "file_menu");
  gtk_widget_ref (file_menu);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "file_menu", file_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (file), file_menu);
  file_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (file_menu));

  exit = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (exit)->child),
                                   _("E_xit"));
  gtk_widget_add_accelerator (exit, "activate_item", file_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (exit, "exit");
  gtk_widget_ref (exit);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "exit", exit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_signal_connect (GTK_OBJECT (exit), "activate",
		      GTK_SIGNAL_FUNC (exit_callback), NULL);
  gtk_widget_show (exit);
  gtk_container_add (GTK_CONTAINER (file_menu), exit);
  gtk_widget_add_accelerator (exit, "activate", accel_group,
                              GDK_x, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  edit = gtk_menu_item_new_with_label (_("Edit"));
  gtk_widget_set_name (edit, "edit");
  gtk_widget_ref (edit);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "edit", edit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (edit);
  gtk_container_add (GTK_CONTAINER (main_menubar), edit);

  select = gtk_menu_item_new_with_label (_("Select"));
  gtk_widget_set_name (select, "select");
  gtk_widget_ref (select);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "select", select,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (select);
  gtk_container_add (GTK_CONTAINER (main_menubar), select);

  camera = gtk_menu_item_new_with_label (_("Camera"));
  gtk_widget_set_name (camera, "camera");
  gtk_widget_ref (camera);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "camera", camera,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (camera);
  gtk_container_add (GTK_CONTAINER (main_menubar), camera);

  camera_menu = gtk_menu_new ();
  gtk_widget_set_name (camera_menu, "camera_menu");
  gtk_widget_ref (camera_menu);
  gtk_object_set_data_full(GTK_OBJECT (main_win), "camera_menu", camera_menu,
			   (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu(GTK_MENU_ITEM (camera), camera_menu);
  camera_menu_accels = gtk_menu_ensure_uline_accel_group
    (GTK_MENU (camera_menu));

  select_camera = gtk_menu_item_new_with_label (_("Select Camera"));
  gtk_widget_set_name (select_camera, "select_camera");
  gtk_widget_ref (select_camera);
  gtk_object_set_data_full(GTK_OBJECT (main_win), "select_camera", 
			   select_camera, (GtkDestroyNotify)gtk_widget_unref);
  gtk_signal_connect (GTK_OBJECT (select_camera), "activate",
                      GTK_SIGNAL_FUNC (select_camera_callback), NULL);
  gtk_widget_show (select_camera);
  gtk_container_add (GTK_CONTAINER (camera_menu), select_camera);
    
  export = gtk_menu_item_new_with_label (_("Export"));
  gtk_widget_set_name (export, "export");
  gtk_widget_ref (export);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "export", export,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (export);
  gtk_container_add (GTK_CONTAINER (main_menubar), export);

  export_menu = gtk_menu_new ();
  gtk_widget_set_name (export_menu, "export_menu");
  gtk_widget_ref (export_menu);
  gtk_object_set_data_full(GTK_OBJECT (main_win), "export_menu", export_menu,
			   (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu(GTK_MENU_ITEM (export), export_menu);

  html_export = gtk_menu_item_new_with_label (_("HTML Export"));
  gtk_widget_set_name (html_export, "html_export");
  gtk_widget_ref (html_export);
  gtk_object_set_data_full(GTK_OBJECT (main_win), "html_export", 
			   html_export, (GtkDestroyNotify)gtk_widget_unref);

  /* this signal will probably have to change if we want to do more
     with the display window function and keep it "generic" */

  gtk_signal_connect(GTK_OBJECT(html_export), "activate", 
		     GTK_SIGNAL_FUNC(display_window), (int *)XPORT_WIN);

  gtk_widget_show (html_export);
  gtk_container_add (GTK_CONTAINER (export_menu), html_export);

  main_toolbar = gtk_toolbar_new(GTK_ORIENTATION_HORIZONTAL,
				 GTK_TOOLBAR_ICONS);
  gtk_widget_set_name (main_toolbar, "main_toolbar");
  gtk_widget_ref (main_toolbar);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "main_toolbar", 
			    main_toolbar, (GtkDestroyNotify)gtk_widget_unref);
  gtk_widget_show (main_toolbar);
  gtk_box_pack_start (GTK_BOX (main_vbox), main_toolbar, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (main_toolbar), 5);

  tmp_toolbar_icon = create_pixmap (main_win, "close_image.xpm");
  button2 = gtk_toolbar_append_element (GTK_TOOLBAR (main_toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button2"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (button2, "button2");
  gtk_widget_ref (button2);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "button2", button2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button2);

  tmp_toolbar_icon = create_pixmap (main_win, "configure.xpm");
  button4 = gtk_toolbar_append_element (GTK_TOOLBAR (main_toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button4"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (button4, "button4");
  gtk_widget_ref (button4);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "button4", button4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button4);

  tmp_toolbar_icon = create_pixmap (main_win, "exit.xpm");
  button5 = gtk_toolbar_append_element (GTK_TOOLBAR (main_toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button5"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (button5, "button5");
  gtk_widget_ref (button5);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "button5", button5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button5);

  hseparator = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator, "hseparator");
  gtk_widget_ref (hseparator);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "hseparator", hseparator,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator);
  gtk_box_pack_start (GTK_BOX (main_vbox), hseparator, FALSE, TRUE, 0);

  main_hpaned = gtk_hpaned_new ();
  gtk_widget_set_name (main_hpaned, "main_hpaned");
  gtk_widget_ref (main_hpaned);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "main_hpaned", main_hpaned,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (main_hpaned);
  gtk_box_pack_start (GTK_BOX (main_vbox), main_hpaned, TRUE, TRUE, 0);
  gtk_paned_set_handle_size (GTK_PANED (main_hpaned), 8);
  gtk_paned_set_position (GTK_PANED (main_hpaned), 0);

  main_hbox_hp = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (main_hbox_hp, "main_hbox_hp");
  gtk_widget_ref (main_hbox_hp);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "main_hbox_hp", 
			    main_hbox_hp,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (main_hbox_hp);
  gtk_paned_pack1 (GTK_PANED (main_hpaned), main_hbox_hp, FALSE, FALSE);
  gtk_widget_set_usize (main_hbox_hp, 175, -2);

  main_vpaned = gtk_vpaned_new ();
  gtk_widget_set_name (main_vpaned, "main_vpaned");
  gtk_widget_ref (main_vpaned);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "main_vpaned", main_vpaned,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (main_vpaned);
  gtk_box_pack_start (GTK_BOX (main_hbox_hp), main_vpaned, TRUE, TRUE, 0);
  gtk_paned_set_handle_size (GTK_PANED (main_vpaned), 6);
  gtk_paned_set_gutter_size (GTK_PANED (main_vpaned), 8);
  gtk_paned_set_position (GTK_PANED (main_vpaned), 0);

  main_vbox_vp = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (main_vbox_vp, "main_vbox_vp");
  gtk_widget_ref (main_vbox_vp);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "main_vbox_vp", 
			    main_vbox_vp,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (main_vbox_vp);
  
  main_label = gtk_label_new("Local Directory Listing");
  gtk_widget_ref(main_label);
  gtk_box_pack_start(GTK_BOX(main_vbox_vp), main_label, FALSE,FALSE,0);
  gtk_widget_show(main_label);
  
  gtk_paned_pack1 (GTK_PANED (main_vpaned), main_vbox_vp, FALSE, FALSE);
  gtk_widget_set_usize (main_vbox_vp, -2, 175);

  main_scroll_local = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (main_scroll_local, "main_scroll_local");
  gtk_widget_ref (main_scroll_local);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "main_scroll_local", 
			    main_scroll_local,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (main_scroll_local);
  gtk_box_pack_start(GTK_BOX(main_vbox_vp), main_scroll_local, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy(GTK_SCROLLED_WINDOW (main_scroll_local), 
				 GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  main_vp_local = gtk_viewport_new (NULL, NULL);
  gtk_widget_set_name (main_vp_local, "main_vp_local");
  gtk_widget_ref (main_vp_local);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "main_vp_local", 
			    main_vp_local,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (main_vp_local);
  gtk_container_add (GTK_CONTAINER (main_scroll_local), main_vp_local);

  /* start local file directory tree */
  main_tree_local = gtk_tree_new ();
  gtk_widget_set_name (main_tree_local, "main_tree_local");
  gtk_widget_ref (main_tree_local);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "main_tree_local", 
			    main_tree_local,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (main_tree_local);
  gtk_container_add (GTK_CONTAINER (main_vp_local), main_tree_local);
  /* end local file directory tree */

  main_vbox_vp = gtk_vbox_new (FALSE, 2);
  gtk_widget_set_name (main_vbox_vp, "main_vbox_vp");
  gtk_widget_ref (main_vbox_vp);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "main_vbox_vp", 
			    main_vbox_vp,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (main_vbox_vp);

  main_label = gtk_label_new("Camera Directory Listing");
  gtk_widget_ref(main_label);
  gtk_box_pack_start(GTK_BOX(main_vbox_vp), main_label, FALSE,FALSE,0);
  gtk_widget_show(main_label);

  gtk_paned_pack2 (GTK_PANED (main_vpaned), main_vbox_vp, TRUE, TRUE);

  main_scroll_cam = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (main_scroll_cam, "main_scroll_cam");
  gtk_widget_ref (main_scroll_cam);
  gtk_object_set_data_full(GTK_OBJECT (main_win), "main_scroll_cam", 
			   main_scroll_cam,
			   (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (main_scroll_cam);
  gtk_box_pack_start(GTK_BOX(main_vbox_vp), main_scroll_cam, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (main_scroll_cam), 
				  GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  main_vp_cam = gtk_viewport_new (NULL, NULL);
  gtk_widget_set_name (main_vp_cam, "main_vp_cam");
  gtk_widget_ref (main_vp_cam);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "main_vp_cam", main_vp_cam,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (main_vp_cam);
  gtk_container_add (GTK_CONTAINER (main_scroll_cam), main_vp_cam);

  /* camera tree list */
  main_tree_cam = gtk_tree_new ();
  gtk_widget_set_name (main_tree_cam, "main_tree_cam");
  gtk_widget_ref (main_tree_cam);
  gtk_object_set_data_full(GTK_OBJECT (main_win), "main_tree_cam", 
			   main_tree_cam, 
			   (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (main_tree_cam);
  gtk_container_add (GTK_CONTAINER (main_vp_cam), main_tree_cam);

  /* this is incomplete in terms of signal code */

  main_leaf_cam = gtk_tree_item_new();
  gtk_widget_ref(main_leaf_cam);
  gtk_tree_append(GTK_TREE(main_tree_cam), main_leaf_cam);
  gtk_widget_show(main_leaf_cam);

  /* tree functions in tree_list_util.c */
  main_tree_hbox = create_camera_tree();
  gtk_container_add(GTK_CONTAINER(main_leaf_cam), main_tree_hbox);
  gtk_widget_show(main_tree_hbox);
  
  /* end camera list tree */

  hseparator = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator, "hseparator");
  gtk_widget_ref (hseparator);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "hseparator", hseparator,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator);
  gtk_box_pack_start (GTK_BOX (main_vbox), hseparator, FALSE, FALSE, 0);

  main_hbox_sb = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (main_hbox_sb, "main_hbox_sb");
  gtk_widget_ref (main_hbox_sb);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "main_hbox_sb", main_hbox_sb,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (main_hbox_sb);
  gtk_box_pack_start (GTK_BOX (main_vbox), main_hbox_sb, FALSE, FALSE, 0);

  main_statbar = gtk_statusbar_new ();
  gtk_widget_set_name (main_statbar, "main_statbar");
  gtk_widget_ref (main_statbar);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "main_statbar", main_statbar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (main_statbar);
  gtk_box_pack_start (GTK_BOX (main_hbox_sb), main_statbar, TRUE, TRUE, 0);
  gtk_widget_set_sensitive (main_statbar, FALSE);

  main_progbar = gtk_progress_bar_new ();
  gtk_widget_set_name (main_progbar, "main_progbar");
  gtk_widget_ref (main_progbar);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "main_progbar", main_progbar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (main_progbar);
  gtk_box_pack_end (GTK_BOX (main_hbox_sb), main_progbar, FALSE, FALSE, 0);
  gtk_progress_set_activity_mode (GTK_PROGRESS (main_progbar), TRUE);

  hseparator = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator, "hseparator");
  gtk_widget_ref (hseparator);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "hseparator", hseparator,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator);
  gtk_box_pack_start (GTK_BOX (main_vbox), hseparator, FALSE, FALSE, 0);

  return main_win;

}

GtkWidget *create_img_win (void) {

  GtkWidget *img_win;
  GtkWidget *img_vbox;
  GtkWidget *img_menubar;
  guint tmp_key;
  GtkWidget *file1;
  GtkWidget *file1_menu;
  GtkAccelGroup *file1_menu_accels;
  GtkWidget *close;
  GtkWidget *hseparator;
  GtkWidget *img_hpaned;
  GtkWidget *img_vbox_hp;
  GtkWidget *img_toolbar;
  GtkWidget *tmp_toolbar_icon;
  GtkWidget *button25;
  GtkWidget *button26;
  GtkWidget *button27;
  GtkWidget *button28;
  GtkWidget *button29;
  GtkWidget *button30;
  GtkWidget *button31;
  GtkWidget *button32;
  GtkWidget *button33;
  GtkWidget *img_label;
  GtkWidget *image;
  GtkWidget *img_scroll;
  GtkWidget *img_scroll_view;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  img_win = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (img_win, "img_win");
  gtk_object_set_data (GTK_OBJECT (img_win), "img_win", img_win);
  gtk_window_set_title (GTK_WINDOW (img_win), _("gphoto2 - Image Window"));
  gtk_window_set_default_size (GTK_WINDOW (img_win), 750, 450);

  img_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (img_vbox, "img_vbox");
  gtk_widget_ref (img_vbox);
  gtk_object_set_data_full (GTK_OBJECT (img_win), "img_vbox", img_vbox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (img_vbox);
  gtk_container_add (GTK_CONTAINER (img_win), img_vbox);

  img_menubar = gtk_menu_bar_new ();
  gtk_widget_set_name (img_menubar, "img_menubar");
  gtk_widget_ref (img_menubar);
  gtk_object_set_data_full (GTK_OBJECT (img_win), "img_menubar", img_menubar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (img_menubar);
  gtk_box_pack_start (GTK_BOX (img_vbox), img_menubar, FALSE, FALSE, 0);

  file1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (file1)->child),
                                   _("_File"));
  gtk_widget_add_accelerator (file1, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, 0);
  gtk_widget_set_name (file1, "file1");
  gtk_widget_ref (file1);
  gtk_object_set_data_full (GTK_OBJECT (img_win), "file1", file1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file1);
  gtk_container_add (GTK_CONTAINER (img_menubar), file1);

  file1_menu = gtk_menu_new ();
  gtk_widget_set_name (file1_menu, "file1_menu");
  gtk_widget_ref (file1_menu);
  gtk_object_set_data_full (GTK_OBJECT (img_win), "file1_menu", file1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (file1), file1_menu);
  file1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (file1_menu));

  close = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (close)->child),
                                   _("_Close"));
  gtk_widget_add_accelerator (close, "activate_item", file1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (close, "close");
  gtk_widget_ref (close);
  gtk_object_set_data_full (GTK_OBJECT (img_win), "close", close,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (close);
  gtk_container_add (GTK_CONTAINER (file1_menu), close);

  hseparator = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator, "hseparator");
  gtk_widget_ref (hseparator);
  gtk_object_set_data_full (GTK_OBJECT (img_win), "hseparator", hseparator,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator);
  gtk_box_pack_start (GTK_BOX (img_vbox), hseparator, FALSE, FALSE, 0);

  img_hpaned = gtk_hpaned_new ();
  gtk_widget_set_name (img_hpaned, "img_hpaned");
  gtk_widget_ref (img_hpaned);
  gtk_object_set_data_full (GTK_OBJECT (img_win), "img_hpaned", img_hpaned,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (img_hpaned);
  gtk_box_pack_start (GTK_BOX (img_vbox), img_hpaned, TRUE, TRUE, 0);
  gtk_paned_set_handle_size (GTK_PANED (img_hpaned), 6);
  gtk_paned_set_position (GTK_PANED (img_hpaned), 1);

  img_vbox_hp = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (img_vbox_hp, "img_vbox_hp");
  gtk_widget_ref (img_vbox_hp);
  gtk_object_set_data_full (GTK_OBJECT (img_win), "img_vbox_hp", img_vbox_hp,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (img_vbox_hp);
  gtk_paned_pack1 (GTK_PANED (img_hpaned), img_vbox_hp, FALSE, FALSE);
  gtk_widget_set_usize (img_vbox_hp, 150, -2);

  img_toolbar = gtk_toolbar_new (GTK_ORIENTATION_HORIZONTAL, GTK_TOOLBAR_ICONS);
  gtk_widget_set_name (img_toolbar, "img_toolbar");
  gtk_widget_ref (img_toolbar);
  gtk_object_set_data_full (GTK_OBJECT (img_win), "img_toolbar", img_toolbar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (img_toolbar);
  gtk_box_pack_start (GTK_BOX (img_vbox_hp), img_toolbar, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (img_toolbar), 5);

  tmp_toolbar_icon = create_pixmap (img_win, "camera.xpm");
  button25 = gtk_toolbar_append_element (GTK_TOOLBAR (img_toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button25"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (button25, "button25");
  gtk_widget_ref (button25);
  gtk_object_set_data_full (GTK_OBJECT (img_win), "button25", button25,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button25);

  tmp_toolbar_icon = create_pixmap (img_win, "close_image.xpm");
  button26 = gtk_toolbar_append_element (GTK_TOOLBAR (img_toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button26"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (button26, "button26");
  gtk_widget_ref (button26);
  gtk_object_set_data_full (GTK_OBJECT (img_win), "button26", button26,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button26);

  tmp_toolbar_icon = create_pixmap (img_win, "delete_images.xpm");
  button27 = gtk_toolbar_append_element (GTK_TOOLBAR (img_toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button27"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (button27, "button27");
  gtk_widget_ref (button27);
  gtk_object_set_data_full (GTK_OBJECT (img_win), "button27", button27,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button27);

  img_toolbar = gtk_toolbar_new (GTK_ORIENTATION_HORIZONTAL, GTK_TOOLBAR_ICONS);
  gtk_widget_set_name (img_toolbar, "img_toolbar");
  gtk_widget_ref (img_toolbar);
  gtk_object_set_data_full (GTK_OBJECT (img_win), "img_toolbar", img_toolbar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (img_toolbar);
  gtk_box_pack_start (GTK_BOX (img_vbox_hp), img_toolbar, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (img_toolbar), 5);

  tmp_toolbar_icon = create_pixmap (img_win, "flipv.xpm");
  button28 = gtk_toolbar_append_element (GTK_TOOLBAR (img_toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button28"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (button28, "button28");
  gtk_widget_ref (button28);
  gtk_object_set_data_full (GTK_OBJECT (img_win), "button28", button28,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button28);

  tmp_toolbar_icon = create_pixmap (img_win, "folder.xpm");
  button29 = gtk_toolbar_append_element (GTK_TOOLBAR (img_toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button29"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (button29, "button29");
  gtk_widget_ref (button29);
  gtk_object_set_data_full (GTK_OBJECT (img_win), "button29", button29,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button29);

  tmp_toolbar_icon = create_pixmap (img_win, "flipv.xpm");
  button30 = gtk_toolbar_append_element (GTK_TOOLBAR (img_toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button30"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (button30, "button30");
  gtk_widget_ref (button30);
  gtk_object_set_data_full (GTK_OBJECT (img_win), "button30", button30,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button30);

  img_toolbar = gtk_toolbar_new (GTK_ORIENTATION_HORIZONTAL, GTK_TOOLBAR_ICONS);
  gtk_widget_set_name (img_toolbar, "img_toolbar");
  gtk_widget_ref (img_toolbar);
  gtk_object_set_data_full (GTK_OBJECT (img_win), "img_toolbar", img_toolbar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (img_toolbar);
  gtk_box_pack_start (GTK_BOX (img_vbox_hp), img_toolbar, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (img_toolbar), 5);

  tmp_toolbar_icon = create_pixmap (img_win, "save_current_image.xpm");
  button31 = gtk_toolbar_append_element (GTK_TOOLBAR (img_toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button31"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (button31, "button31");
  gtk_widget_ref (button31);
  gtk_object_set_data_full (GTK_OBJECT (img_win), "button31", button31,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button31);

  tmp_toolbar_icon = create_pixmap (img_win, "open_image.xpm");
  button32 = gtk_toolbar_append_element (GTK_TOOLBAR (img_toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button32"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (button32, "button32");
  gtk_widget_ref (button32);
  gtk_object_set_data_full (GTK_OBJECT (img_win), "button32", button32,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button32);

  tmp_toolbar_icon = create_pixmap (img_win, "print_image.xpm");
  button33 = gtk_toolbar_append_element (GTK_TOOLBAR (img_toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button33"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (button33, "button33");
  gtk_widget_ref (button33);
  gtk_object_set_data_full (GTK_OBJECT (img_win), "button33", button33,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button33);

  hseparator = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator, "hseparator");
  gtk_widget_ref (hseparator);
  gtk_object_set_data_full (GTK_OBJECT (img_win), "hseparator", hseparator,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator);
  gtk_box_pack_start (GTK_BOX (img_vbox_hp), hseparator, FALSE, FALSE, 0);

  img_label = gtk_label_new (_("image name"));
  gtk_widget_set_name (img_label, "img_label");
  gtk_widget_ref (img_label);
  gtk_object_set_data_full (GTK_OBJECT (img_win), "img_label", img_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (img_label);
  gtk_box_pack_start (GTK_BOX (img_vbox_hp), img_label, FALSE, FALSE, 0);

  hseparator = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator, "hseparator");
  gtk_widget_ref (hseparator);
  gtk_object_set_data_full (GTK_OBJECT (img_win), "hseparator", hseparator,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator);
  gtk_box_pack_start (GTK_BOX (img_vbox_hp), hseparator, FALSE, FALSE, 0);

  image = gtk_image_new (gdk_image_new (GDK_IMAGE_NORMAL, gdk_visual_get_system (), 100, 100), NULL);
  gtk_widget_set_name (image, "image");
  gtk_widget_ref (image);
  gtk_object_set_data_full (GTK_OBJECT (img_win), "image", image,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (image);
  gtk_box_pack_start (GTK_BOX (img_vbox_hp), image, TRUE, TRUE, 0);

  img_scroll = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (img_scroll, "img_scroll");
  gtk_widget_ref (img_scroll);
  gtk_object_set_data_full (GTK_OBJECT (img_win), "img_scroll", img_scroll,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (img_scroll);
  gtk_paned_pack2 (GTK_PANED (img_hpaned), img_scroll, TRUE, TRUE);

  img_scroll_view = gtk_viewport_new (NULL, NULL);
  gtk_widget_set_name (img_scroll_view, "img_scroll_view");
  gtk_widget_ref (img_scroll_view);
  gtk_object_set_data_full (GTK_OBJECT (img_win), "img_scroll_view", img_scroll_view,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (img_scroll_view);
  gtk_container_add (GTK_CONTAINER (img_scroll), img_scroll_view);

  image = gtk_image_new (gdk_image_new (GDK_IMAGE_NORMAL, gdk_visual_get_system (), 250, 250), NULL);
  gtk_widget_set_name (image, "image");
  gtk_widget_ref (image);
  gtk_object_set_data_full (GTK_OBJECT (img_win), "image", image,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (image);
  gtk_container_add (GTK_CONTAINER (img_scroll_view), image);

  gtk_signal_connect (GTK_OBJECT (close), "activate",
                      GTK_SIGNAL_FUNC (close_callback),
                      img_win);

  gtk_window_add_accel_group (GTK_WINDOW (img_win), accel_group);

  return img_win;
}

GtkWidget *create_xport_win (void) {
  
  GtkWidget *xport_win;
  GtkWidget *xport_vbox;
  GtkWidget *xport_menubar;
  guint tmp_key;
  GtkWidget *file;
  GtkWidget *file_menu;
  GtkAccelGroup *file_menu_accels;
  GtkWidget *close;
  GtkWidget *xport_toolbar;
  GtkWidget *tmp_toolbar_icon;
  GtkWidget *button41;
  GtkWidget *button42;
  GtkWidget *button43;
  GtkWidget *hseparator;
  GtkWidget *xport_hbox_gal;
  GtkWidget *xport_label_gal;
  GtkWidget *vseparator;
  GtkWidget *xport_entry_gal;
  GtkWidget *xport_hbox_label;
  GtkWidget *export_label_avail;
  GtkWidget *xport_vbox_img;
  GtkWidget *xport_scroll_avail;
  GtkWidget *xport_vp_avail;
  GtkWidget *xport_list_avail;
  GtkWidget *xport_vbox_img_func;
  GtkWidget *xport_button_add;
  GtkWidget *xport_button_remove;
  GtkWidget *xport_button_up;
  GtkWidget *xport_button_down;
  GtkWidget *xport_label_preview;
  GtkWidget *xport_img_preview;
  GtkWidget *xport_scroll_gal;
  GtkWidget *xport_vp_gal;
  GtkWidget *xport_list_gal;
  GtkWidget *xport_hbox_caption;
  GtkWidget *xport_label_caption;
  GtkWidget *xport_entry_caption;
  GtkWidget *xport_hbox_theme;
  GtkWidget *xport_option_theme;
  GtkWidget *xport_option_theme_menu;
  GtkWidget *glade_menuitem;
  GtkWidget *xport_button_create;
  GtkWidget *xport_button_done;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  xport_win = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (xport_win, "xport_win");
  gtk_object_set_data (GTK_OBJECT (xport_win), "xport_win", xport_win);
  gtk_window_set_title (GTK_WINDOW (xport_win), _("gphoto2 - Gallery Export"));
  gtk_window_set_default_size (GTK_WINDOW (xport_win), 550, 450);

  xport_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (xport_vbox, "xport_vbox");
  gtk_widget_ref (xport_vbox);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "xport_vbox", xport_vbox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (xport_vbox);
  gtk_container_add (GTK_CONTAINER (xport_win), xport_vbox);

  xport_menubar = gtk_menu_bar_new ();
  gtk_widget_set_name (xport_menubar, "xport_menubar");
  gtk_widget_ref (xport_menubar);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "xport_menubar", xport_menubar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (xport_menubar);
  gtk_box_pack_start (GTK_BOX (xport_vbox), xport_menubar, FALSE, FALSE, 0);

  file = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (file)->child),
                                   _("_File"));
  gtk_widget_add_accelerator (file, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, 0);
  gtk_widget_set_name (file, "file");
  gtk_widget_ref (file);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "file", file,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file);
  gtk_container_add (GTK_CONTAINER (xport_menubar), file);

  file_menu = gtk_menu_new ();
  gtk_widget_set_name (file_menu, "file_menu");
  gtk_widget_ref (file_menu);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "file_menu", file_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (file), file_menu);
  file_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (file_menu));

  close = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (close)->child),
                                   _("_Close"));
  gtk_widget_add_accelerator (close, "activate_item", file_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (close, "close");
  gtk_widget_ref (close);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "close", close,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (close);
  gtk_container_add (GTK_CONTAINER (file_menu), close);
  gtk_widget_add_accelerator (close, "activate", accel_group,
                              GDK_C, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  xport_toolbar = gtk_toolbar_new (GTK_ORIENTATION_HORIZONTAL, GTK_TOOLBAR_ICONS);
  gtk_widget_set_name (xport_toolbar, "xport_toolbar");
  gtk_widget_ref (xport_toolbar);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "xport_toolbar", xport_toolbar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (xport_toolbar);
  gtk_box_pack_start (GTK_BOX (xport_vbox), xport_toolbar, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (xport_toolbar), 5);

  tmp_toolbar_icon = create_pixmap (xport_win, "close_image.xpm");
  button41 = gtk_toolbar_append_element (GTK_TOOLBAR (xport_toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button41"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (button41, "button41");
  gtk_widget_ref (button41);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "button41", button41,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button41);

  tmp_toolbar_icon = create_pixmap (xport_win, "flipv.xpm");
  button42 = gtk_toolbar_append_element (GTK_TOOLBAR (xport_toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button42"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (button42, "button42");
  gtk_widget_ref (button42);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "button42", button42,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button42);

  tmp_toolbar_icon = create_pixmap (xport_win, "get_index.xpm");
  button43 = gtk_toolbar_append_element (GTK_TOOLBAR (xport_toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button43"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (button43, "button43");
  gtk_widget_ref (button43);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "button43", button43,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button43);

  hseparator = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator, "hseparator");
  gtk_widget_ref (hseparator);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "hseparator", hseparator,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator);
  gtk_box_pack_start (GTK_BOX (xport_vbox), hseparator, FALSE, FALSE, 2);

  xport_hbox_gal = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (xport_hbox_gal, "xport_hbox_gal");
  gtk_widget_ref (xport_hbox_gal);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "xport_hbox_gal", xport_hbox_gal,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (xport_hbox_gal);
  gtk_box_pack_start (GTK_BOX (xport_vbox), xport_hbox_gal, FALSE, TRUE, 0);

  xport_label_gal = gtk_label_new (_("Gallery Name"));
  gtk_widget_set_name (xport_label_gal, "xport_label_gal");
  gtk_widget_ref (xport_label_gal);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "xport_label_gal", xport_label_gal,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (xport_label_gal);
  gtk_box_pack_start (GTK_BOX (xport_hbox_gal), xport_label_gal, FALSE, FALSE, 5);

  vseparator = gtk_vseparator_new ();
  gtk_widget_set_name (vseparator, "vseparator");
  gtk_widget_ref (vseparator);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "vseparator", vseparator,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vseparator);
  gtk_box_pack_start (GTK_BOX (xport_hbox_gal), vseparator, FALSE, FALSE, 0);

  xport_entry_gal = gtk_entry_new ();
  gtk_widget_set_name (xport_entry_gal, "xport_entry_gal");
  gtk_widget_ref (xport_entry_gal);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "xport_entry_gal", xport_entry_gal,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (xport_entry_gal);
  gtk_box_pack_start (GTK_BOX (xport_hbox_gal), xport_entry_gal, TRUE, TRUE, 5);

  hseparator = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator, "hseparator");
  gtk_widget_ref (hseparator);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "hseparator", hseparator,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator);
  gtk_box_pack_start (GTK_BOX (xport_vbox), hseparator, FALSE, FALSE, 2);

  xport_hbox_label = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (xport_hbox_label, "xport_hbox_label");
  gtk_widget_ref (xport_hbox_label);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "xport_hbox_label", xport_hbox_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (xport_hbox_label);
  gtk_box_pack_start (GTK_BOX (xport_vbox), xport_hbox_label, FALSE, TRUE, 0);

  export_label_avail = gtk_label_new (_("Available Images"));
  gtk_widget_set_name (export_label_avail, "export_label_avail");
  gtk_widget_ref (export_label_avail);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "export_label_avail", export_label_avail,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (export_label_avail);
  gtk_box_pack_start (GTK_BOX (xport_hbox_label), export_label_avail, FALSE, FALSE, 25);

  xport_label_gal = gtk_label_new (_("Gallery Images"));
  gtk_widget_set_name (xport_label_gal, "xport_label_gal");
  gtk_widget_ref (xport_label_gal);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "xport_label_gal", xport_label_gal,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (xport_label_gal);
  gtk_box_pack_end (GTK_BOX (xport_hbox_label), xport_label_gal, FALSE, FALSE, 50);

  hseparator = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator, "hseparator");
  gtk_widget_ref (hseparator);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "hseparator", hseparator,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator);
  gtk_box_pack_start (GTK_BOX (xport_vbox), hseparator, FALSE, FALSE, 2);

  xport_vbox_img = gtk_hbox_new (TRUE, 0);
  gtk_widget_set_name (xport_vbox_img, "xport_vbox_img");
  gtk_widget_ref (xport_vbox_img);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "xport_vbox_img", xport_vbox_img,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (xport_vbox_img);
  gtk_box_pack_start (GTK_BOX (xport_vbox), xport_vbox_img, TRUE, TRUE, 0);

  xport_scroll_avail = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (xport_scroll_avail, "xport_scroll_avail");
  gtk_widget_ref (xport_scroll_avail);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "xport_scroll_avail", xport_scroll_avail,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (xport_scroll_avail);
  gtk_box_pack_start (GTK_BOX (xport_vbox_img), xport_scroll_avail, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (xport_scroll_avail), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  xport_vp_avail = gtk_viewport_new (NULL, NULL);
  gtk_widget_set_name (xport_vp_avail, "xport_vp_avail");
  gtk_widget_ref (xport_vp_avail);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "xport_vp_avail", xport_vp_avail,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (xport_vp_avail);
  gtk_container_add (GTK_CONTAINER (xport_scroll_avail), xport_vp_avail);

  xport_list_avail = gtk_list_new ();
  gtk_widget_set_name (xport_list_avail, "xport_list_avail");
  gtk_widget_ref (xport_list_avail);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "xport_list_avail", xport_list_avail,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (xport_list_avail);
  gtk_container_add (GTK_CONTAINER (xport_vp_avail), xport_list_avail);

  xport_vbox_img_func = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (xport_vbox_img_func, "xport_vbox_img_func");
  gtk_widget_ref (xport_vbox_img_func);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "xport_vbox_img_func", xport_vbox_img_func,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (xport_vbox_img_func);
  gtk_box_pack_start (GTK_BOX (xport_vbox_img), xport_vbox_img_func, TRUE, FALSE, 0);

  xport_button_add = gtk_button_new_with_label (_("Add"));
  gtk_widget_set_name (xport_button_add, "xport_button_add");
  gtk_widget_ref (xport_button_add);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "xport_button_add", xport_button_add,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (xport_button_add);
  gtk_box_pack_start (GTK_BOX (xport_vbox_img_func), xport_button_add, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (xport_button_add), 5);
  gtk_tooltips_set_tip (tooltips, xport_button_add, _("Add selected image to gallery"), NULL);

  xport_button_remove = gtk_button_new_with_label (_("Remove"));
  gtk_widget_set_name (xport_button_remove, "xport_button_remove");
  gtk_widget_ref (xport_button_remove);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "xport_button_remove", xport_button_remove,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (xport_button_remove);
  gtk_box_pack_start (GTK_BOX (xport_vbox_img_func), xport_button_remove, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (xport_button_remove), 5);
  gtk_tooltips_set_tip (tooltips, xport_button_remove, _("Remove selected image from gallery"), NULL);

  xport_button_up = gtk_button_new_with_label (_("Up"));
  gtk_widget_set_name (xport_button_up, "xport_button_up");
  gtk_widget_ref (xport_button_up);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "xport_button_up", xport_button_up,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (xport_button_up);
  gtk_box_pack_start (GTK_BOX (xport_vbox_img_func), xport_button_up, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (xport_button_up), 5);
  gtk_tooltips_set_tip (tooltips, xport_button_up, _("Move selected image location up"), NULL);

  xport_button_down = gtk_button_new_with_label (_("Down"));
  gtk_widget_set_name (xport_button_down, "xport_button_down");
  gtk_widget_ref (xport_button_down);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "xport_button_down", xport_button_down,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (xport_button_down);
  gtk_box_pack_start (GTK_BOX (xport_vbox_img_func), xport_button_down, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (xport_button_down), 5);
  gtk_tooltips_set_tip (tooltips, xport_button_down, _("Move selected image location down"), NULL);

  hseparator = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator, "hseparator");
  gtk_widget_ref (hseparator);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "hseparator", hseparator,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator);
  gtk_box_pack_start (GTK_BOX (xport_vbox_img_func), hseparator, FALSE, FALSE, 5);

  xport_label_preview = gtk_label_new (_("Image Preview"));
  gtk_widget_set_name (xport_label_preview, "xport_label_preview");
  gtk_widget_ref (xport_label_preview);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "xport_label_preview", xport_label_preview,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (xport_label_preview);
  gtk_box_pack_start (GTK_BOX (xport_vbox_img_func), xport_label_preview, FALSE, FALSE, 0);

  hseparator = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator, "hseparator");
  gtk_widget_ref (hseparator);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "hseparator", hseparator,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator);
  gtk_box_pack_start (GTK_BOX (xport_vbox_img_func), hseparator, FALSE, FALSE, 5);

  xport_img_preview = gtk_image_new (gdk_image_new (GDK_IMAGE_NORMAL, gdk_visual_get_system (), 100, 100), NULL);
  gtk_widget_set_name (xport_img_preview, "xport_img_preview");
  gtk_widget_ref (xport_img_preview);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "xport_img_preview", xport_img_preview,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (xport_img_preview);
  gtk_box_pack_start (GTK_BOX (xport_vbox_img_func), xport_img_preview, TRUE, TRUE, 0);

  xport_scroll_gal = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (xport_scroll_gal, "xport_scroll_gal");
  gtk_widget_ref (xport_scroll_gal);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "xport_scroll_gal", xport_scroll_gal,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (xport_scroll_gal);
  gtk_box_pack_start (GTK_BOX (xport_vbox_img), xport_scroll_gal, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (xport_scroll_gal), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  xport_vp_gal = gtk_viewport_new (NULL, NULL);
  gtk_widget_set_name (xport_vp_gal, "xport_vp_gal");
  gtk_widget_ref (xport_vp_gal);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "xport_vp_gal", xport_vp_gal,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (xport_vp_gal);
  gtk_container_add (GTK_CONTAINER (xport_scroll_gal), xport_vp_gal);

  xport_list_gal = gtk_list_new ();
  gtk_widget_set_name (xport_list_gal, "xport_list_gal");
  gtk_widget_ref (xport_list_gal);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "xport_list_gal", xport_list_gal,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (xport_list_gal);
  gtk_container_add (GTK_CONTAINER (xport_vp_gal), xport_list_gal);

  hseparator = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator, "hseparator");
  gtk_widget_ref (hseparator);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "hseparator", hseparator,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator);
  gtk_box_pack_start (GTK_BOX (xport_vbox), hseparator, FALSE, FALSE, 2);

  xport_hbox_caption = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (xport_hbox_caption, "xport_hbox_caption");
  gtk_widget_ref (xport_hbox_caption);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "xport_hbox_caption", xport_hbox_caption,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (xport_hbox_caption);
  gtk_box_pack_start (GTK_BOX (xport_vbox), xport_hbox_caption, FALSE, FALSE, 0);

  xport_label_caption = gtk_label_new (_("Image Caption"));
  gtk_widget_set_name (xport_label_caption, "xport_label_caption");
  gtk_widget_ref (xport_label_caption);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "xport_label_caption", xport_label_caption,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (xport_label_caption);
  gtk_box_pack_start (GTK_BOX (xport_hbox_caption), xport_label_caption, FALSE, FALSE, 5);

  vseparator = gtk_vseparator_new ();
  gtk_widget_set_name (vseparator, "vseparator");
  gtk_widget_ref (vseparator);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "vseparator", vseparator,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vseparator);
  gtk_box_pack_start (GTK_BOX (xport_hbox_caption), vseparator, FALSE, FALSE, 0);

  xport_entry_caption = gtk_entry_new ();
  gtk_widget_set_name (xport_entry_caption, "xport_entry_caption");
  gtk_widget_ref (xport_entry_caption);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "xport_entry_caption", xport_entry_caption,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (xport_entry_caption);
  gtk_box_pack_start (GTK_BOX (xport_hbox_caption), xport_entry_caption, TRUE, TRUE, 5);

  hseparator = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator, "hseparator");
  gtk_widget_ref (hseparator);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "hseparator", hseparator,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator);
  gtk_box_pack_start (GTK_BOX (xport_vbox), hseparator, FALSE, FALSE, 2);

  xport_hbox_theme = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (xport_hbox_theme, "xport_hbox_theme");
  gtk_widget_ref (xport_hbox_theme);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "xport_hbox_theme", xport_hbox_theme,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (xport_hbox_theme);
  gtk_box_pack_start (GTK_BOX (xport_vbox), xport_hbox_theme, FALSE, FALSE, 0);

  xport_option_theme = gtk_option_menu_new ();
  gtk_widget_set_name (xport_option_theme, "xport_option_theme");
  gtk_widget_ref (xport_option_theme);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "xport_option_theme", xport_option_theme,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (xport_option_theme);
  gtk_box_pack_start (GTK_BOX (xport_hbox_theme), xport_option_theme, FALSE, FALSE, 0);
  xport_option_theme_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Select Gallery Theme"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (xport_option_theme_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (xport_option_theme), xport_option_theme_menu);

  xport_button_done = gtk_button_new_with_label (_("Done"));
  gtk_widget_set_name (xport_button_done, "xport_button_done");
  gtk_widget_ref (xport_button_done);
  gtk_object_set_data_full(GTK_OBJECT (xport_win), "xport_button_done", 
			   xport_button_done, (GtkDestroyNotify) 
			   gtk_widget_unref);

  gtk_signal_connect(GTK_OBJECT(xport_button_done), "clicked",
		     GTK_SIGNAL_FUNC(close_callback), xport_win);

  gtk_widget_show (xport_button_done);
  gtk_box_pack_end (GTK_BOX (xport_hbox_theme), xport_button_done, FALSE, 
		    FALSE, 5);

  xport_button_create = gtk_button_new_with_label (_("Create Gallery"));
  gtk_widget_set_name (xport_button_create, "xport_button_create");
  gtk_widget_ref (xport_button_create);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "xport_button_create", xport_button_create,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (xport_button_create);
  gtk_box_pack_end(GTK_BOX (xport_hbox_theme), xport_button_create, FALSE, FALSE, 5);
  
  hseparator = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator, "hseparator");
  gtk_widget_ref (hseparator);
  gtk_object_set_data_full (GTK_OBJECT (xport_win), "hseparator", hseparator,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator);
  gtk_box_pack_start (GTK_BOX (xport_vbox), hseparator, FALSE, FALSE, 2);

  gtk_signal_connect (GTK_OBJECT (close), "activate",
                      GTK_SIGNAL_FUNC (close_callback),
                      xport_win);

  gtk_object_set_data (GTK_OBJECT (xport_win), "tooltips", tooltips);

  gtk_window_add_accel_group (GTK_WINDOW (xport_win), accel_group);

  return xport_win;
}

