/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#ifndef WITHOUT_GNOME
#include <gnome.h>
#include <glade/glade.h>
#endif

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *main_win;

#ifdef ENABLE_NLS
  bindtextdomain (PACKAGE, PACKAGE_LOCALE_DIR);
  textdomain (PACKAGE);
#endif

  gtk_set_locale ();
#ifdef WITHOUT_GNOME
  gtk_init (&argc, &argv);
#else
  gnome_init (PACKAGE, VERSION, argc, argv);
  glade_gnome_init ();
  gtk_widget_push_visual (gdk_imlib_get_visual ());
  gtk_widget_push_colormap (gdk_imlib_get_colormap ());
#endif

  add_pixmap_directory (PACKAGE_DATA_DIR "/pixmaps");
  add_pixmap_directory (PACKAGE_SOURCE_DIR "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  main_win = create_main_win ();
  gtk_widget_show (main_win);

  gtk_main ();
  return 0;
}

