BASEPATH=..\..


all: start \
  dll \
  end

!include $(BASEPATH)\os2mak.inc

dll: $(CAMLIBS)\gpdigita.dll

OBJS=digita.o \
     digita.def \
     serial.o \
     commands.o \
     usb.o

.c.o:
   @$(CC) -o $@ $< $(CCFLAGS)

digita.def: digita.o
   @$(MAKEDEF)

$(CAMLIBS)\gpdigita.dll: $(OBJS)
   @$(LINK) $(DLLLINKFLAGS) -o $@ $** $(LIBS) -lsocket -lgiserial -L..\..\lib
