/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_main_window (void);
GtkWidget* create_message_window_long (void);
GtkWidget* create_confirm_window (void);
GtkWidget* create_message_window (void);
GtkWidget* create_select_camera_window (void);
