/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>
#include <gphoto2.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

int interface_message(char *message) {

	return (GP_OK);
}

int interface_status(char *message) {

	return (GP_OK);
}

int interface_progress(float percentage) {

	return (GP_OK);
}

int interface_confirm(char *message) {

	return (GP_OK);
}


GtkWidget*
create_main_window (void)
{
  GtkWidget *main_window;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  guint tmp_key;
  GtkWidget *file2;
  GtkWidget *file2_menu;
  GtkAccelGroup *file2_menu_accels;
  GtkWidget *open3;
  GtkWidget *open3_menu;
  GtkAccelGroup *open3_menu_accels;
  GtkWidget *photo1;
  GtkWidget *directory1;
  GtkWidget *save1;
  GtkWidget *save1_menu;
  GtkAccelGroup *save1_menu_accels;
  GtkWidget *opened_photo1;
  GtkWidget *selected_photo1;
  GtkWidget *separator2;
  GtkWidget *export1;
  GtkWidget *export1_menu;
  GtkAccelGroup *export1_menu_accels;
  GtkWidget *html_gallery1;
  GtkWidget *separator5;
  GtkWidget *print1;
  GtkWidget *close1;
  GtkWidget *exit1;
  GtkWidget *edit1;
  GtkWidget *edit1_menu;
  GtkAccelGroup *edit1_menu_accels;
  GtkWidget *flip1;
  GtkWidget *flip1_menu;
  GtkAccelGroup *flip1_menu_accels;
  GtkWidget *horizontal1;
  GtkWidget *vertical1;
  GtkWidget *rotate1;
  GtkWidget *rotate1_menu;
  GtkAccelGroup *rotate1_menu_accels;
  GtkWidget *_90_degrees1;
  GtkWidget *_180_degrees1;
  GtkWidget *_270_degrees1;
  GtkWidget *size1;
  GtkWidget *size1_menu;
  GtkAccelGroup *size1_menu_accels;
  GtkWidget *scale1;
  GtkWidget *scale_half1;
  GtkWidget *scale_double1;
  GtkWidget *select1;
  GtkWidget *select1_menu;
  GtkAccelGroup *select1_menu_accels;
  GtkWidget *all1;
  GtkWidget *inverse1;
  GtkWidget *none1;
  GtkWidget *camera1;
  GtkWidget *camera1_menu;
  GtkAccelGroup *camera1_menu_accels;
  GtkWidget *select2;
  GtkWidget *separator6;
  GtkWidget *download_index1;
  GtkWidget *download_index1_menu;
  GtkAccelGroup *download_index1_menu_accels;
  GtkWidget *thumbnails1;
  GtkWidget *no_thumbnails1;
  GtkWidget *download_selected1;
  GtkWidget *download_selected1_menu;
  GtkAccelGroup *download_selected1_menu_accels;
  GtkWidget *thumbnails2;
  GtkWidget *photos1;
  GtkWidget *both1;
  GtkWidget *delete1;
  GtkWidget *delete1_menu;
  GtkAccelGroup *delete1_menu_accels;
  GtkWidget *selected_photos1;
  GtkWidget *all_images1;
  GtkWidget *separator3;
  GtkWidget *configure1;
  GtkWidget *information1;
  GtkWidget *manual1;
  GtkWidget *about_the_driver1;
  GtkWidget *help1;
  GtkWidget *help1_menu;
  GtkAccelGroup *help1_menu_accels;
  GtkWidget *user_s_manual1;
  GtkWidget *authors1;
  GtkWidget *license1;
  GtkWidget *about_gphoto1;
  GtkWidget *toolbar1;
  GtkWidget *tmp_toolbar_icon;
  GtkWidget *open_button;
  GtkWidget *save_button;
  GtkWidget *print_button;
  GtkWidget *close_button;
  GtkWidget *label1;
  GtkWidget *index_button;
  GtkWidget *index_empty_button;
  GtkWidget *download_button;
  GtkWidget *delete_button;
  GtkWidget *label2;
  GtkWidget *rotate_button;
  GtkWidget *flip_horizontal_button;
  GtkWidget *flip_vertical_button;
  GtkWidget *scale_button;
  GtkWidget *label4;
  GtkWidget *configure_button;
  GtkWidget *label5;
  GtkWidget *exit_button;
  GtkWidget *hpaned1;
  GtkWidget *vbox2;
  GtkWidget *camera_model_label;
  GtkWidget *scrolledwindow1;
  GtkWidget *viewport1;
  GtkWidget *tree1;
  GtkWidget *progress_bar;
  GtkWidget *scrolledwindow2;
  GtkWidget *viewport2;
  GtkWidget *table1;
  GtkWidget *status_bar;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  main_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (main_window), "main_window", main_window);
  gtk_window_set_title (GTK_WINDOW (main_window), _("gPhoto2"));
  gtk_window_set_position (GTK_WINDOW (main_window), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (main_window), 640, 480);

  vbox1 = gtk_vbox_new (FALSE, 1);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (main_window), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_ref (menubar1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "menubar1", menubar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  file2 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (file2)->child),
                                   _("_File"));
  gtk_widget_add_accelerator (file2, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (file2);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "file2", file2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file2);
  gtk_container_add (GTK_CONTAINER (menubar1), file2);

  file2_menu = gtk_menu_new ();
  gtk_widget_ref (file2_menu);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "file2_menu", file2_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (file2), file2_menu);
  file2_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (file2_menu));

  open3 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (open3)->child),
                                   _("_Open"));
  gtk_widget_add_accelerator (open3, "activate_item", file2_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (open3);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "open3", open3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (open3);
  gtk_container_add (GTK_CONTAINER (file2_menu), open3);

  open3_menu = gtk_menu_new ();
  gtk_widget_ref (open3_menu);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "open3_menu", open3_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (open3), open3_menu);
  open3_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (open3_menu));

  photo1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (photo1)->child),
                                   _("_Photo..."));
  gtk_widget_add_accelerator (photo1, "activate_item", open3_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (photo1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "photo1", photo1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (photo1);
  gtk_container_add (GTK_CONTAINER (open3_menu), photo1);
  gtk_widget_add_accelerator (photo1, "activate", accel_group,
                              GDK_o, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  directory1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (directory1)->child),
                                   _("_Directory..."));
  gtk_widget_add_accelerator (directory1, "activate_item", open3_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (directory1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "directory1", directory1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (directory1);
  gtk_container_add (GTK_CONTAINER (open3_menu), directory1);
  gtk_widget_add_accelerator (directory1, "activate", accel_group,
                              GDK_d, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  save1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (save1)->child),
                                   _("_Save"));
  gtk_widget_add_accelerator (save1, "activate_item", file2_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (save1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "save1", save1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (save1);
  gtk_container_add (GTK_CONTAINER (file2_menu), save1);

  save1_menu = gtk_menu_new ();
  gtk_widget_ref (save1_menu);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "save1_menu", save1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (save1), save1_menu);
  save1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (save1_menu));

  opened_photo1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (opened_photo1)->child),
                                   _("_Opened Photo(s).."));
  gtk_widget_add_accelerator (opened_photo1, "activate_item", save1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (opened_photo1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "opened_photo1", opened_photo1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (opened_photo1);
  gtk_container_add (GTK_CONTAINER (save1_menu), opened_photo1);
  gtk_widget_add_accelerator (opened_photo1, "activate", accel_group,
                              GDK_s, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  selected_photo1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (selected_photo1)->child),
                                   _("_Selected Photo(s)..."));
  gtk_widget_add_accelerator (selected_photo1, "activate_item", save1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (selected_photo1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "selected_photo1", selected_photo1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (selected_photo1);
  gtk_container_add (GTK_CONTAINER (save1_menu), selected_photo1);
  gtk_widget_add_accelerator (selected_photo1, "activate", accel_group,
                              GDK_i, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  separator2 = gtk_menu_item_new ();
  gtk_widget_ref (separator2);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "separator2", separator2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator2);
  gtk_container_add (GTK_CONTAINER (file2_menu), separator2);
  gtk_widget_set_sensitive (separator2, FALSE);

  export1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (export1)->child),
                                   _("_Export"));
  gtk_widget_add_accelerator (export1, "activate_item", file2_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (export1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "export1", export1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (export1);
  gtk_container_add (GTK_CONTAINER (file2_menu), export1);

  export1_menu = gtk_menu_new ();
  gtk_widget_ref (export1_menu);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "export1_menu", export1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (export1), export1_menu);
  export1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (export1_menu));

  html_gallery1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (html_gallery1)->child),
                                   _("_HTML Gallery"));
  gtk_widget_add_accelerator (html_gallery1, "activate_item", export1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (html_gallery1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "html_gallery1", html_gallery1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (html_gallery1);
  gtk_container_add (GTK_CONTAINER (export1_menu), html_gallery1);

  separator5 = gtk_menu_item_new ();
  gtk_widget_ref (separator5);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "separator5", separator5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator5);
  gtk_container_add (GTK_CONTAINER (file2_menu), separator5);
  gtk_widget_set_sensitive (separator5, FALSE);

  print1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (print1)->child),
                                   _("_Print"));
  gtk_widget_add_accelerator (print1, "activate_item", file2_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (print1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "print1", print1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (print1);
  gtk_container_add (GTK_CONTAINER (file2_menu), print1);
  gtk_widget_add_accelerator (print1, "activate", accel_group,
                              GDK_p, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  close1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (close1)->child),
                                   _("_Close"));
  gtk_widget_add_accelerator (close1, "activate_item", file2_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (close1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "close1", close1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (close1);
  gtk_container_add (GTK_CONTAINER (file2_menu), close1);
  gtk_widget_add_accelerator (close1, "activate", accel_group,
                              GDK_c, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  exit1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (exit1)->child),
                                   _("_Exit"));
  gtk_widget_add_accelerator (exit1, "activate_item", file2_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (exit1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "exit1", exit1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (exit1);
  gtk_container_add (GTK_CONTAINER (file2_menu), exit1);
  gtk_widget_add_accelerator (exit1, "activate", accel_group,
                              GDK_x, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  edit1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (edit1)->child),
                                   _("_Edit"));
  gtk_widget_add_accelerator (edit1, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (edit1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "edit1", edit1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (edit1);
  gtk_container_add (GTK_CONTAINER (menubar1), edit1);

  edit1_menu = gtk_menu_new ();
  gtk_widget_ref (edit1_menu);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "edit1_menu", edit1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (edit1), edit1_menu);
  edit1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (edit1_menu));

  flip1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (flip1)->child),
                                   _("_Flip"));
  gtk_widget_add_accelerator (flip1, "activate_item", edit1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (flip1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "flip1", flip1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (flip1);
  gtk_container_add (GTK_CONTAINER (edit1_menu), flip1);

  flip1_menu = gtk_menu_new ();
  gtk_widget_ref (flip1_menu);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "flip1_menu", flip1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (flip1), flip1_menu);
  flip1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (flip1_menu));

  horizontal1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (horizontal1)->child),
                                   _("_Horizontal"));
  gtk_widget_add_accelerator (horizontal1, "activate_item", flip1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (horizontal1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "horizontal1", horizontal1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (horizontal1);
  gtk_container_add (GTK_CONTAINER (flip1_menu), horizontal1);

  vertical1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (vertical1)->child),
                                   _("_Vertical"));
  gtk_widget_add_accelerator (vertical1, "activate_item", flip1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (vertical1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "vertical1", vertical1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vertical1);
  gtk_container_add (GTK_CONTAINER (flip1_menu), vertical1);

  rotate1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (rotate1)->child),
                                   _("_Rotate"));
  gtk_widget_add_accelerator (rotate1, "activate_item", edit1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (rotate1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "rotate1", rotate1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (rotate1);
  gtk_container_add (GTK_CONTAINER (edit1_menu), rotate1);

  rotate1_menu = gtk_menu_new ();
  gtk_widget_ref (rotate1_menu);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "rotate1_menu", rotate1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (rotate1), rotate1_menu);
  rotate1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (rotate1_menu));

  _90_degrees1 = gtk_menu_item_new_with_label (_("90 degrees"));
  gtk_widget_ref (_90_degrees1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "_90_degrees1", _90_degrees1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (_90_degrees1);
  gtk_container_add (GTK_CONTAINER (rotate1_menu), _90_degrees1);
  gtk_widget_add_accelerator (_90_degrees1, "activate", accel_group,
                              GDK_r, GDK_SHIFT_MASK,
                              GTK_ACCEL_VISIBLE);

  _180_degrees1 = gtk_menu_item_new_with_label (_("180 degrees"));
  gtk_widget_ref (_180_degrees1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "_180_degrees1", _180_degrees1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (_180_degrees1);
  gtk_container_add (GTK_CONTAINER (rotate1_menu), _180_degrees1);

  _270_degrees1 = gtk_menu_item_new_with_label (_("270 degrees"));
  gtk_widget_ref (_270_degrees1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "_270_degrees1", _270_degrees1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (_270_degrees1);
  gtk_container_add (GTK_CONTAINER (rotate1_menu), _270_degrees1);

  size1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (size1)->child),
                                   _("_Size"));
  gtk_widget_add_accelerator (size1, "activate_item", edit1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (size1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "size1", size1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (size1);
  gtk_container_add (GTK_CONTAINER (edit1_menu), size1);

  size1_menu = gtk_menu_new ();
  gtk_widget_ref (size1_menu);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "size1_menu", size1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (size1), size1_menu);
  size1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (size1_menu));

  scale1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (scale1)->child),
                                   _("_Scale"));
  gtk_widget_add_accelerator (scale1, "activate_item", size1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (scale1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "scale1", scale1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scale1);
  gtk_container_add (GTK_CONTAINER (size1_menu), scale1);
  gtk_widget_add_accelerator (scale1, "activate", accel_group,
                              GDK_s, GDK_SHIFT_MASK,
                              GTK_ACCEL_VISIBLE);

  scale_half1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (scale_half1)->child),
                                   _("Scale _Half"));
  gtk_widget_add_accelerator (scale_half1, "activate_item", size1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (scale_half1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "scale_half1", scale_half1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scale_half1);
  gtk_container_add (GTK_CONTAINER (size1_menu), scale_half1);
  gtk_widget_add_accelerator (scale_half1, "activate", accel_group,
                              GDK_h, GDK_SHIFT_MASK,
                              GTK_ACCEL_VISIBLE);

  scale_double1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (scale_double1)->child),
                                   _("Scale _Double"));
  gtk_widget_add_accelerator (scale_double1, "activate_item", size1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (scale_double1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "scale_double1", scale_double1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scale_double1);
  gtk_container_add (GTK_CONTAINER (size1_menu), scale_double1);
  gtk_widget_add_accelerator (scale_double1, "activate", accel_group,
                              GDK_d, GDK_SHIFT_MASK,
                              GTK_ACCEL_VISIBLE);

  select1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (select1)->child),
                                   _("_Select"));
  gtk_widget_add_accelerator (select1, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (select1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "select1", select1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (select1);
  gtk_container_add (GTK_CONTAINER (menubar1), select1);

  select1_menu = gtk_menu_new ();
  gtk_widget_ref (select1_menu);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "select1_menu", select1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (select1), select1_menu);
  select1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (select1_menu));

  all1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (all1)->child),
                                   _("_All"));
  gtk_widget_add_accelerator (all1, "activate_item", select1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (all1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "all1", all1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (all1);
  gtk_container_add (GTK_CONTAINER (select1_menu), all1);
  gtk_widget_add_accelerator (all1, "activate", accel_group,
                              GDK_a, GDK_SHIFT_MASK,
                              GTK_ACCEL_VISIBLE);

  inverse1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (inverse1)->child),
                                   _("_Inverse"));
  gtk_widget_add_accelerator (inverse1, "activate_item", select1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (inverse1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "inverse1", inverse1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (inverse1);
  gtk_container_add (GTK_CONTAINER (select1_menu), inverse1);
  gtk_widget_add_accelerator (inverse1, "activate", accel_group,
                              GDK_i, GDK_SHIFT_MASK,
                              GTK_ACCEL_VISIBLE);

  none1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (none1)->child),
                                   _("_None"));
  gtk_widget_add_accelerator (none1, "activate_item", select1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (none1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "none1", none1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (none1);
  gtk_container_add (GTK_CONTAINER (select1_menu), none1);
  gtk_widget_add_accelerator (none1, "activate", accel_group,
                              GDK_n, GDK_SHIFT_MASK,
                              GTK_ACCEL_VISIBLE);

  camera1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (camera1)->child),
                                   _("_Camera"));
  gtk_widget_add_accelerator (camera1, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (camera1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "camera1", camera1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (camera1);
  gtk_container_add (GTK_CONTAINER (menubar1), camera1);

  camera1_menu = gtk_menu_new ();
  gtk_widget_ref (camera1_menu);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "camera1_menu", camera1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (camera1), camera1_menu);
  camera1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (camera1_menu));

  select2 = gtk_menu_item_new_with_label (_("Select Camera..."));
  gtk_widget_ref (select2);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "select2", select2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (select2);
  gtk_container_add (GTK_CONTAINER (camera1_menu), select2);
  gtk_widget_add_accelerator (select2, "activate", accel_group,
                              GDK_c, GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);

  separator6 = gtk_menu_item_new ();
  gtk_widget_ref (separator6);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "separator6", separator6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator6);
  gtk_container_add (GTK_CONTAINER (camera1_menu), separator6);
  gtk_widget_set_sensitive (separator6, FALSE);

  download_index1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (download_index1)->child),
                                   _("Download _Index"));
  gtk_widget_add_accelerator (download_index1, "activate_item", camera1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (download_index1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "download_index1", download_index1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (download_index1);
  gtk_container_add (GTK_CONTAINER (camera1_menu), download_index1);

  download_index1_menu = gtk_menu_new ();
  gtk_widget_ref (download_index1_menu);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "download_index1_menu", download_index1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (download_index1), download_index1_menu);
  download_index1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (download_index1_menu));

  thumbnails1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (thumbnails1)->child),
                                   _("_Thumbnails"));
  gtk_widget_add_accelerator (thumbnails1, "activate_item", download_index1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (thumbnails1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "thumbnails1", thumbnails1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (thumbnails1);
  gtk_container_add (GTK_CONTAINER (download_index1_menu), thumbnails1);
  gtk_widget_add_accelerator (thumbnails1, "activate", accel_group,
                              GDK_i, GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);

  no_thumbnails1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (no_thumbnails1)->child),
                                   _("_No Thumbnails"));
  gtk_widget_add_accelerator (no_thumbnails1, "activate_item", download_index1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (no_thumbnails1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "no_thumbnails1", no_thumbnails1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (no_thumbnails1);
  gtk_container_add (GTK_CONTAINER (download_index1_menu), no_thumbnails1);
  gtk_widget_add_accelerator (no_thumbnails1, "activate", accel_group,
                              GDK_e, GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);

  download_selected1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (download_selected1)->child),
                                   _("Download _Selected"));
  gtk_widget_add_accelerator (download_selected1, "activate_item", camera1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (download_selected1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "download_selected1", download_selected1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (download_selected1);
  gtk_container_add (GTK_CONTAINER (camera1_menu), download_selected1);

  download_selected1_menu = gtk_menu_new ();
  gtk_widget_ref (download_selected1_menu);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "download_selected1_menu", download_selected1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (download_selected1), download_selected1_menu);
  download_selected1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (download_selected1_menu));

  thumbnails2 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (thumbnails2)->child),
                                   _("_Thumbnails"));
  gtk_widget_add_accelerator (thumbnails2, "activate_item", download_selected1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (thumbnails2);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "thumbnails2", thumbnails2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (thumbnails2);
  gtk_container_add (GTK_CONTAINER (download_selected1_menu), thumbnails2);
  gtk_widget_add_accelerator (thumbnails2, "activate", accel_group,
                              GDK_t, GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);

  photos1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (photos1)->child),
                                   _("_Photos"));
  gtk_widget_add_accelerator (photos1, "activate_item", download_selected1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (photos1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "photos1", photos1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (photos1);
  gtk_container_add (GTK_CONTAINER (download_selected1_menu), photos1);
  gtk_widget_add_accelerator (photos1, "activate", accel_group,
                              GDK_p, GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);

  both1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (both1)->child),
                                   _("_Both"));
  gtk_widget_add_accelerator (both1, "activate_item", download_selected1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (both1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "both1", both1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (both1);
  gtk_container_add (GTK_CONTAINER (download_selected1_menu), both1);
  gtk_widget_add_accelerator (both1, "activate", accel_group,
                              GDK_b, GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);

  delete1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (delete1)->child),
                                   _("_Delete"));
  gtk_widget_add_accelerator (delete1, "activate_item", camera1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (delete1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "delete1", delete1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (delete1);
  gtk_container_add (GTK_CONTAINER (camera1_menu), delete1);

  delete1_menu = gtk_menu_new ();
  gtk_widget_ref (delete1_menu);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "delete1_menu", delete1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (delete1), delete1_menu);
  delete1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (delete1_menu));

  selected_photos1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (selected_photos1)->child),
                                   _("_Selected Photos"));
  gtk_widget_add_accelerator (selected_photos1, "activate_item", delete1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (selected_photos1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "selected_photos1", selected_photos1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (selected_photos1);
  gtk_container_add (GTK_CONTAINER (delete1_menu), selected_photos1);
  gtk_widget_add_accelerator (selected_photos1, "activate", accel_group,
                              GDK_d, GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);

  all_images1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (all_images1)->child),
                                   _("_All Images"));
  gtk_widget_add_accelerator (all_images1, "activate_item", delete1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (all_images1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "all_images1", all_images1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (all_images1);
  gtk_container_add (GTK_CONTAINER (delete1_menu), all_images1);
  gtk_widget_add_accelerator (all_images1, "activate", accel_group,
                              GDK_a, GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);

  separator3 = gtk_menu_item_new ();
  gtk_widget_ref (separator3);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "separator3", separator3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator3);
  gtk_container_add (GTK_CONTAINER (camera1_menu), separator3);
  gtk_widget_set_sensitive (separator3, FALSE);

  configure1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (configure1)->child),
                                   _("_Configure..."));
  gtk_widget_add_accelerator (configure1, "activate_item", camera1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (configure1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "configure1", configure1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (configure1);
  gtk_container_add (GTK_CONTAINER (camera1_menu), configure1);

  information1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (information1)->child),
                                   _("_Information..."));
  gtk_widget_add_accelerator (information1, "activate_item", camera1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (information1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "information1", information1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (information1);
  gtk_container_add (GTK_CONTAINER (camera1_menu), information1);

  manual1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (manual1)->child),
                                   _("_Manual..."));
  gtk_widget_add_accelerator (manual1, "activate_item", camera1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (manual1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "manual1", manual1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (manual1);
  gtk_container_add (GTK_CONTAINER (camera1_menu), manual1);

  about_the_driver1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (about_the_driver1)->child),
                                   _("_About the driver..."));
  gtk_widget_add_accelerator (about_the_driver1, "activate_item", camera1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (about_the_driver1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "about_the_driver1", about_the_driver1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (about_the_driver1);
  gtk_container_add (GTK_CONTAINER (camera1_menu), about_the_driver1);

  help1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (help1)->child),
                                   _("_Help"));
  gtk_widget_add_accelerator (help1, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (help1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "help1", help1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (help1);
  gtk_container_add (GTK_CONTAINER (menubar1), help1);

  help1_menu = gtk_menu_new ();
  gtk_widget_ref (help1_menu);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "help1_menu", help1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help1), help1_menu);
  help1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (help1_menu));

  user_s_manual1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (user_s_manual1)->child),
                                   _("_User's Manual..."));
  gtk_widget_add_accelerator (user_s_manual1, "activate_item", help1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (user_s_manual1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "user_s_manual1", user_s_manual1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (user_s_manual1);
  gtk_container_add (GTK_CONTAINER (help1_menu), user_s_manual1);
  gtk_widget_add_accelerator (user_s_manual1, "activate", accel_group,
                              GDK_m, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  authors1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (authors1)->child),
                                   _("_Authors..."));
  gtk_widget_add_accelerator (authors1, "activate_item", help1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (authors1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "authors1", authors1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (authors1);
  gtk_container_add (GTK_CONTAINER (help1_menu), authors1);

  license1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (license1)->child),
                                   _("_License..."));
  gtk_widget_add_accelerator (license1, "activate_item", help1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (license1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "license1", license1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (license1);
  gtk_container_add (GTK_CONTAINER (help1_menu), license1);

  about_gphoto1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (about_gphoto1)->child),
                                   _("About _gPhoto..."));
  gtk_widget_add_accelerator (about_gphoto1, "activate_item", help1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (about_gphoto1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "about_gphoto1", about_gphoto1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (about_gphoto1);
  gtk_container_add (GTK_CONTAINER (help1_menu), about_gphoto1);
  gtk_widget_add_accelerator (about_gphoto1, "activate", accel_group,
                              GDK_a, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  toolbar1 = gtk_toolbar_new (GTK_ORIENTATION_HORIZONTAL, GTK_TOOLBAR_ICONS);
  gtk_widget_ref (toolbar1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "toolbar1", toolbar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), toolbar1, FALSE, FALSE, 0);

  tmp_toolbar_icon = create_pixmap (main_window, "open_image.xpm");
  open_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button1"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (open_button);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "open_button", open_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (open_button);

  tmp_toolbar_icon = create_pixmap (main_window, "save_current_image.xpm");
  save_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button2"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (save_button);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "save_button", save_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (save_button);

  tmp_toolbar_icon = create_pixmap (main_window, "print_image.xpm");
  print_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button3"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (print_button);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "print_button", print_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (print_button);

  tmp_toolbar_icon = create_pixmap (main_window, "close_image.xpm");
  close_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button4"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (close_button);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "close_button", close_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (close_button);

  label1 = gtk_label_new (_("       "));
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar1), label1, NULL, NULL);

  tmp_toolbar_icon = create_pixmap (main_window, "get_index.xpm");
  index_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button5"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (index_button);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "index_button", index_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (index_button);

  tmp_toolbar_icon = create_pixmap (main_window, "get_index_empty.xpm");
  index_empty_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button6"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (index_empty_button);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "index_empty_button", index_empty_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (index_empty_button);

  tmp_toolbar_icon = create_pixmap (main_window, "get_selected_images.xpm");
  download_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button7"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (download_button);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "download_button", download_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (download_button);

  tmp_toolbar_icon = create_pixmap (main_window, "delete_images.xpm");
  delete_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "",
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (delete_button);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "delete_button", delete_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (delete_button);

  label2 = gtk_label_new (_("       "));
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar1), label2, NULL, NULL);

  tmp_toolbar_icon = create_pixmap (main_window, "rotc.xpm");
  rotate_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button10"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (rotate_button);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "rotate_button", rotate_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (rotate_button);

  tmp_toolbar_icon = create_pixmap (main_window, "fliph.xpm");
  flip_horizontal_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button12"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (flip_horizontal_button);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "flip_horizontal_button", flip_horizontal_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (flip_horizontal_button);

  tmp_toolbar_icon = create_pixmap (main_window, "flipv.xpm");
  flip_vertical_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button13"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (flip_vertical_button);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "flip_vertical_button", flip_vertical_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (flip_vertical_button);

  tmp_toolbar_icon = create_pixmap (main_window, "resize.xpm");
  scale_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button14"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (scale_button);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "scale_button", scale_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scale_button);

  label4 = gtk_label_new (_("       "));
  gtk_widget_ref (label4);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label4);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar1), label4, NULL, NULL);

  tmp_toolbar_icon = create_pixmap (main_window, "configure.xpm");
  configure_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button15"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (configure_button);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "configure_button", configure_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (configure_button);

  label5 = gtk_label_new (_("       "));
  gtk_widget_ref (label5);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "label5", label5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label5);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar1), label5, NULL, NULL);

  tmp_toolbar_icon = create_pixmap (main_window, "exit.xpm");
  exit_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button16"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (exit_button);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "exit_button", exit_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (exit_button);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_ref (hpaned1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "hpaned1", hpaned1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hpaned1);
  gtk_box_pack_start (GTK_BOX (vbox1), hpaned1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hpaned1), 2);
  gtk_paned_set_position (GTK_PANED (hpaned1), 200);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_paned_pack1 (GTK_PANED (hpaned1), vbox2, FALSE, TRUE);

  camera_model_label = gtk_label_new (_("No Camera Selected"));
  gtk_widget_ref (camera_model_label);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "camera_model_label", camera_model_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (camera_model_label);
  gtk_box_pack_start (GTK_BOX (vbox2), camera_model_label, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (camera_model_label), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (camera_model_label), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (camera_model_label), 0, 5);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox2), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_ref (viewport1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "viewport1", viewport1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), viewport1);

  tree1 = gtk_tree_new ();
  gtk_widget_ref (tree1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "tree1", tree1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tree1);
  gtk_container_add (GTK_CONTAINER (viewport1), tree1);

  progress_bar = gtk_progress_bar_new ();
  gtk_widget_ref (progress_bar);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "progress_bar", progress_bar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (progress_bar);
  gtk_box_pack_start (GTK_BOX (vbox2), progress_bar, FALSE, FALSE, 0);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow2);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "scrolledwindow2", scrolledwindow2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow2);
  gtk_paned_pack2 (GTK_PANED (hpaned1), scrolledwindow2, TRUE, TRUE);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  viewport2 = gtk_viewport_new (NULL, NULL);
  gtk_widget_ref (viewport2);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "viewport2", viewport2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (viewport2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), viewport2);

  table1 = gtk_table_new (100, 5, FALSE);
  gtk_widget_ref (table1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (viewport2), table1);

  status_bar = gtk_statusbar_new ();
  gtk_widget_ref (status_bar);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "status_bar", status_bar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (status_bar);
  gtk_box_pack_start (GTK_BOX (vbox1), status_bar, FALSE, FALSE, 0);

  gtk_signal_connect (GTK_OBJECT (photo1), "activate",
                      GTK_SIGNAL_FUNC (on_open_photo_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (directory1), "activate",
                      GTK_SIGNAL_FUNC (on_open_directory_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (opened_photo1), "activate",
                      GTK_SIGNAL_FUNC (on_save_open_photo_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (selected_photo1), "activate",
                      GTK_SIGNAL_FUNC (on_save_photo_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (html_gallery1), "activate",
                      GTK_SIGNAL_FUNC (on_html_gallery_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (print1), "activate",
                      GTK_SIGNAL_FUNC (on_print_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (close1), "activate",
                      GTK_SIGNAL_FUNC (on_close_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (exit1), "activate",
                      GTK_SIGNAL_FUNC (on_exit_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (horizontal1), "activate",
                      GTK_SIGNAL_FUNC (on_flip_horizontal_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (vertical1), "activate",
                      GTK_SIGNAL_FUNC (on_flip_vertical_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (_90_degrees1), "activate",
                      GTK_SIGNAL_FUNC (on_90_degrees_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (_180_degrees1), "activate",
                      GTK_SIGNAL_FUNC (on_180_degrees_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (_270_degrees1), "activate",
                      GTK_SIGNAL_FUNC (on_270_degrees_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (scale1), "activate",
                      GTK_SIGNAL_FUNC (on_scale_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (scale_half1), "activate",
                      GTK_SIGNAL_FUNC (on_scale_half_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (scale_double1), "activate",
                      GTK_SIGNAL_FUNC (on_scale_double_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (all1), "activate",
                      GTK_SIGNAL_FUNC (on_select_all_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (inverse1), "activate",
                      GTK_SIGNAL_FUNC (on_select_inverse_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (none1), "activate",
                      GTK_SIGNAL_FUNC (on_select_none_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (select2), "activate",
                      GTK_SIGNAL_FUNC (on_select_camera_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (thumbnails1), "activate",
                      GTK_SIGNAL_FUNC (on_index_thumbnails_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (no_thumbnails1), "activate",
                      GTK_SIGNAL_FUNC (on_index_no_thumbnails_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (thumbnails2), "activate",
                      GTK_SIGNAL_FUNC (on_download_thumbnails_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (photos1), "activate",
                      GTK_SIGNAL_FUNC (on_download_photos_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (both1), "activate",
                      GTK_SIGNAL_FUNC (on_download_both_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (selected_photos1), "activate",
                      GTK_SIGNAL_FUNC (on_delete_photos_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (all_images1), "activate",
                      GTK_SIGNAL_FUNC (on_delete_all_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (configure1), "activate",
                      GTK_SIGNAL_FUNC (on_configure_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (information1), "activate",
                      GTK_SIGNAL_FUNC (on_driver_information_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (manual1), "activate",
                      GTK_SIGNAL_FUNC (on_driver_manual_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (about_the_driver1), "activate",
                      GTK_SIGNAL_FUNC (on_driver_about_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (user_s_manual1), "activate",
                      GTK_SIGNAL_FUNC (on_manual_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (authors1), "activate",
                      GTK_SIGNAL_FUNC (on_authors_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (license1), "activate",
                      GTK_SIGNAL_FUNC (on_license_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (about_gphoto1), "activate",
                      GTK_SIGNAL_FUNC (on_about_activate),
                      NULL);

  gtk_window_add_accel_group (GTK_WINDOW (main_window), accel_group);

  return main_window;
}

GtkWidget*
create_message_window_long (void)
{
  GtkWidget *message_window_long;
  GtkWidget *vbox3;
  GtkWidget *scrolledwindow4;
  GtkWidget *message_window_text;
  GtkWidget *hbox1;
  GtkWidget *message_window_close;

  message_window_long = gtk_window_new (GTK_WINDOW_DIALOG);
  gtk_object_set_data (GTK_OBJECT (message_window_long), "message_window_long", message_window_long);
  gtk_window_set_title (GTK_WINDOW (message_window_long), _("gPhoto2 Long Message"));
  gtk_window_set_position (GTK_WINDOW (message_window_long), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (message_window_long), TRUE);
  gtk_window_set_default_size (GTK_WINDOW (message_window_long), 400, 400);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox3);
  gtk_object_set_data_full (GTK_OBJECT (message_window_long), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (message_window_long), vbox3);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow4);
  gtk_object_set_data_full (GTK_OBJECT (message_window_long), "scrolledwindow4", scrolledwindow4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow4);
  gtk_box_pack_start (GTK_BOX (vbox3), scrolledwindow4, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  message_window_text = gtk_text_new (NULL, NULL);
  gtk_widget_ref (message_window_text);
  gtk_object_set_data_full (GTK_OBJECT (message_window_long), "message_window_text", message_window_text,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (message_window_text);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), message_window_text);

  hbox1 = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (message_window_long), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox1, FALSE, FALSE, 0);

  message_window_close = gtk_button_new_with_label (_("    Close    "));
  gtk_widget_ref (message_window_close);
  gtk_object_set_data_full (GTK_OBJECT (message_window_long), "message_window_close", message_window_close,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (message_window_close);
  gtk_box_pack_start (GTK_BOX (hbox1), message_window_close, FALSE, FALSE, 0);

  return message_window_long;
}

GtkWidget*
create_confirm_window (void)
{
  GtkWidget *confirm_window;
  GtkWidget *vbox4;
  GtkWidget *confirm_label;
  GtkWidget *hbox2;
  GtkWidget *button19;
  GtkWidget *button20;

  confirm_window = gtk_window_new (GTK_WINDOW_DIALOG);
  gtk_object_set_data (GTK_OBJECT (confirm_window), "confirm_window", confirm_window);
  gtk_window_set_title (GTK_WINDOW (confirm_window), _("gPhoto2 Confirmation"));
  gtk_window_set_position (GTK_WINDOW (confirm_window), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (confirm_window), TRUE);
  gtk_window_set_default_size (GTK_WINDOW (confirm_window), 350, 200);

  vbox4 = gtk_vbox_new (FALSE, 7);
  gtk_widget_ref (vbox4);
  gtk_object_set_data_full (GTK_OBJECT (confirm_window), "vbox4", vbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (confirm_window), vbox4);

  confirm_label = gtk_label_new (_("Are you sure?"));
  gtk_widget_ref (confirm_label);
  gtk_object_set_data_full (GTK_OBJECT (confirm_window), "confirm_label", confirm_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (confirm_label);
  gtk_box_pack_start (GTK_BOX (vbox4), confirm_label, TRUE, TRUE, 0);

  hbox2 = gtk_hbox_new (TRUE, 5);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (confirm_window), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox2, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox2), 5);

  button19 = gtk_button_new_with_label (_("Yes"));
  gtk_widget_ref (button19);
  gtk_object_set_data_full (GTK_OBJECT (confirm_window), "button19", button19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button19);
  gtk_box_pack_start (GTK_BOX (hbox2), button19, FALSE, TRUE, 0);

  button20 = gtk_button_new_with_label (_("No"));
  gtk_widget_ref (button20);
  gtk_object_set_data_full (GTK_OBJECT (confirm_window), "button20", button20,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button20);
  gtk_box_pack_start (GTK_BOX (hbox2), button20, FALSE, TRUE, 0);

  return confirm_window;
}

GtkWidget*
create_message_window (void)
{
  GtkWidget *message_window;
  GtkWidget *vbox5;
  GtkWidget *label8;
  GtkWidget *hbox3;
  GtkWidget *button21;

  message_window = gtk_window_new (GTK_WINDOW_DIALOG);
  gtk_object_set_data (GTK_OBJECT (message_window), "message_window", message_window);
  gtk_window_set_title (GTK_WINDOW (message_window), _("gPhoto2 Message"));
  gtk_window_set_position (GTK_WINDOW (message_window), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (message_window), TRUE);
  gtk_window_set_default_size (GTK_WINDOW (message_window), 350, 200);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox5);
  gtk_object_set_data_full (GTK_OBJECT (message_window), "vbox5", vbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox5);
  gtk_container_add (GTK_CONTAINER (message_window), vbox5);

  label8 = gtk_label_new (_("No message."));
  gtk_widget_ref (label8);
  gtk_object_set_data_full (GTK_OBJECT (message_window), "label8", label8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (vbox5), label8, TRUE, TRUE, 0);
  gtk_label_set_line_wrap (GTK_LABEL (label8), TRUE);

  hbox3 = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (message_window), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox3, FALSE, FALSE, 0);

  button21 = gtk_button_new_with_label (_("    Close    "));
  gtk_widget_ref (button21);
  gtk_object_set_data_full (GTK_OBJECT (message_window), "button21", button21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button21);
  gtk_box_pack_start (GTK_BOX (hbox3), button21, FALSE, FALSE, 0);

  return message_window;
}

GtkWidget*
create_select_camera_window (void)
{
  GtkWidget *select_camera_window;
  GtkWidget *vbox6;
  GtkWidget *hbox5;
  GtkWidget *vbox7;
  GtkWidget *label9;
  GtkWidget *camera_combo;
  GtkWidget *combo_entry1;
  GtkWidget *vbox8;
  GtkWidget *label10;
  GtkWidget *port_combo;
  GtkWidget *combo_entry2;
  GtkWidget *hbox4;
  GtkWidget *button23;
  GtkWidget *button24;

  select_camera_window = gtk_window_new (GTK_WINDOW_DIALOG);
  gtk_object_set_data (GTK_OBJECT (select_camera_window), "select_camera_window", select_camera_window);
  gtk_window_set_title (GTK_WINDOW (select_camera_window), _("Select Camera"));
  gtk_window_set_position (GTK_WINDOW (select_camera_window), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (select_camera_window), TRUE);
  gtk_window_set_default_size (GTK_WINDOW (select_camera_window), 300, 150);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox6);
  gtk_object_set_data_full (GTK_OBJECT (select_camera_window), "vbox6", vbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (select_camera_window), vbox6);

  hbox5 = gtk_hbox_new (FALSE, 15);
  gtk_widget_ref (hbox5);
  gtk_object_set_data_full (GTK_OBJECT (select_camera_window), "hbox5", hbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox5, TRUE, TRUE, 0);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox7);
  gtk_object_set_data_full (GTK_OBJECT (select_camera_window), "vbox7", vbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox7);
  gtk_box_pack_start (GTK_BOX (hbox5), vbox7, TRUE, TRUE, 0);

  label9 = gtk_label_new (_("Select Model:"));
  gtk_widget_ref (label9);
  gtk_object_set_data_full (GTK_OBJECT (select_camera_window), "label9", label9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (vbox7), label9, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label9), 0, 0.5);

  camera_combo = gtk_combo_new ();
  gtk_widget_ref (camera_combo);
  gtk_object_set_data_full (GTK_OBJECT (select_camera_window), "camera_combo", camera_combo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (camera_combo);
  gtk_box_pack_start (GTK_BOX (vbox7), camera_combo, FALSE, FALSE, 0);

  combo_entry1 = GTK_COMBO (camera_combo)->entry;
  gtk_widget_ref (combo_entry1);
  gtk_object_set_data_full (GTK_OBJECT (select_camera_window), "combo_entry1", combo_entry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry1);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox8);
  gtk_object_set_data_full (GTK_OBJECT (select_camera_window), "vbox8", vbox8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox8);
  gtk_box_pack_start (GTK_BOX (vbox6), vbox8, TRUE, TRUE, 0);

  label10 = gtk_label_new (_("Select Port:"));
  gtk_widget_ref (label10);
  gtk_object_set_data_full (GTK_OBJECT (select_camera_window), "label10", label10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (vbox8), label10, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label10), 0, 0.5);

  port_combo = gtk_combo_new ();
  gtk_widget_ref (port_combo);
  gtk_object_set_data_full (GTK_OBJECT (select_camera_window), "port_combo", port_combo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (port_combo);
  gtk_box_pack_start (GTK_BOX (vbox8), port_combo, FALSE, FALSE, 0);

  combo_entry2 = GTK_COMBO (port_combo)->entry;
  gtk_widget_ref (combo_entry2);
  gtk_object_set_data_full (GTK_OBJECT (select_camera_window), "combo_entry2", combo_entry2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry2);

  hbox4 = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (hbox4);
  gtk_object_set_data_full (GTK_OBJECT (select_camera_window), "hbox4", hbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox4, FALSE, TRUE, 0);

  button23 = gtk_button_new_with_label (_("OK"));
  gtk_widget_ref (button23);
  gtk_object_set_data_full (GTK_OBJECT (select_camera_window), "button23", button23,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button23);
  gtk_box_pack_start (GTK_BOX (hbox4), button23, FALSE, TRUE, 0);

  button24 = gtk_button_new_with_label (_("Cancel"));
  gtk_widget_ref (button24);
  gtk_object_set_data_full (GTK_OBJECT (select_camera_window), "button24", button24,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button24);
  gtk_box_pack_start (GTK_BOX (hbox4), button24, FALSE, TRUE, 0);

  return select_camera_window;
}
