/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_main_window (void);
GtkWidget* create_save_window (int directory_only);
GtkWidget* create_confirm_window (void);
GtkWidget* create_progress_window (void);
GtkWidget* create_message_window (void);
GtkWidget* create_message_window_long (void);
GtkWidget* create_message_window_transient (void);
GtkWidget* create_message_window_notebook (void);
void message_window_notebook_append(GtkWidget *window, char *label, char *text);

GtkWidget* create_select_camera_window (void);

int gp_interface_message(Camera *camera, char *message);
int gp_interface_message_long(Camera *camera, char *message);
int gp_interface_status(Camera *camera, char *message);
int gp_interface_progress(Camera *camera, CameraFile *file, float percentage);
int gp_interface_confirm(Camera *camera, char *message);
