/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
# include <config.h>
#endif

#include <gtk/gtk.h>
#include <gphoto2.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget *main_window;
int	   gp_gtk_debug=1;

int
main (int argc, char *argv[])
{

#ifdef ENABLE_NLS
	bindtextdomain (PACKAGE, PACKAGE_LOCALE_DIR);
	textdomain (PACKAGE);
#endif

	gtk_set_locale ();
	gtk_init (&argc, &argv);
	gp_init();	

	add_pixmap_directory (PACKAGE_DATA_DIR "/pixmaps");
	add_pixmap_directory (PACKAGE_SOURCE_DIR "/pixmaps");

	/*
	 * The following code was added by Glade to create one of each component
	 * (except popup menus), just so that you see something after building
	 * the project. Delete any components that you don't want shown initially.
	 */
	main_window = create_main_window ();
	
	gtk_widget_show (main_window);
	gtk_signal_connect (GTK_OBJECT(main_window), "delete_event",
		GTK_SIGNAL_FUNC(main_quit), NULL);
	
	gtk_main ();
	return 0;
}
