BASEPATH=..\..

all: start \
  dll \
  end

!include $(BASEPATH)\os2mak.inc

OBJS=util.o \
     serial.o \
     canon.o \
     psa50.o \
     crc.o \
     canon.def \

.c.o :
   @$(CC) -o $@ $< $(CCFLAGS)

canon.def: canon.o
   @$(MAKEDEF)

dll: $(CAMLIBS)\gpcanon.dll

$(CAMLIBS)\gpcanon.dll: $(OBJS)
   @$(LINK) $(DLLLINKFLAGS) -o $@ $** $(LIBS)
