BASEPATH=..\..

all: start \
  cmdline \
  end

!include $(BASEPATH)\os2mak.inc

OBJS=$(OBJPATH)\interface.o \
     $(OBJPATH)\script.o \
     $(OBJPATH)\main.o \
     $(OBJPATH)\test.o \
     $(OBJPATH)\actions.o \
     $(OBJPATH)\shell.o \
     $(OBJPATH)\foreach.o \
     $(OBJPATH)\options.o \
     $(OBJPATH)\range.o

cmdline: $(BASEPATH)\gphoto2.exe

.c{$(OBJPATH)}.o:
  @$(CC) -o $(OBJPATH)\$(@B).o $< $(CCFLAGS)

$(BASEPATH)\gphoto2.exe: $(OBJS)
  @$(LINK) $** -o $@ $(EXELINKFLAGS) $(LIBS)
