BASEPATH=..\..

all: start \
  dll \
  lib \
  end

!include $(BASEPATH)\OS2MAK.INC

dll: $(IOLIBS)\giserial.dll

OBJS=unix.o

.c.o:
   @$(CC) -o $@ $< $(CCFLAGS)

lib: $(BASEPATH)\lib\giserial.a

$(BASEPATH)\lib\giserial.a:
   @implib giserial.lib $(IOLIBS)\giserial.dll
   @emximp -o $(BASEPATH)\lib\giserial.a giserial.lib

serial.def: unix.o
   @$(MAKEDEF)

$(IOLIBS)\giserial.dll: $(OBJS) serial.def
   @$(LINK) $(DLLLINKFLAGS) -o $@ $** $(LIBS)
