BASEPATH=..\..

all: start \
  dll1000 \
  dll1580 \
  end

!include $(BASEPATH)\OS2MAK.INC

dll1000: ..\gpdc1000.dll
dll1580: ..\gpdc1580.dll

OBJS1000=dc.o  dc1000.o
OBJS1580=dc.o  dc1580.o

.c.o:
   @$(CC) -o $@ $< $(CCFLAGS)

dc1000.def: dc1000.o
   @$(MAKEDEF)

..\gpdc1000.dll: $(OBJS1000) dc1000.def
   @$(LINK) $(DLLLINKFLAGS) -o $@ $** $(LIBS)

dc1580.def: dc1580.o
   @$(MAKEDEF)

..\gpdc1580.dll: $(OBJS1580) dc1580.def
   @$(LINK) $(DLLLINKFLAGS) -o $@ $** $(LIBS)
