BASEPATH=..\..

all: start \
  dll \
  end

!include $(BASEPATH)\os2mak.inc

dll: $(CAMLIBS)\gpbarbie.dll

OBJS= barbie.o \
      library.o

.c.o:
   @$(CC) -o $@ $< $(CCFLAGS)

barbie.def: barbie.o
   @$(MAKEDEF)

$(CAMLIBS)\gpbarbie.dll: $(OBJS) barbie.def
   $(LINK) $(DLLLINKFLAGS) -o $@ $** $(LIBS)
