BASEPATH=..\..

all: start \
  dll \
  end

!include $(BASEPATH)\OS2MAK.INC

dll: ..\gpsierra.dll

OBJS=sierra.o library.o sierra-usbwrap.o

.c.o :
   @$(CC) -o $@ $< $(CCFLAGS)

sierra.def: sierra.o
   @$(MAKEDEF)

..\gpsierra.dll: $(OBJS) sierra.def
   @$(LINK) $(DLLLINKFLAGS) -o $@ $** $(LIBS)
