# Generated automatically from Makefile.in by configure.
# Makefile.in generated automatically by automake 1.5 from Makefile.am.

# Copyright 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001
# Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



SHELL = /bin/sh

srcdir = .
top_srcdir = ../..
prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include
pkgdatadir = $(datadir)/gphoto
pkglibdir = $(libdir)/gphoto
pkgincludedir = $(includedir)/gphoto
top_builddir = ../..

ACLOCAL = ${SHELL} /home/scottf/Desktop/projects/sourceforge/gphoto2/missing --run aclocal
AUTOCONF = ${SHELL} /home/scottf/Desktop/projects/sourceforge/gphoto2/missing --run autoconf
AUTOMAKE = ${SHELL} /home/scottf/Desktop/projects/sourceforge/gphoto2/missing --run automake
AUTOHEADER = ${SHELL} /home/scottf/Desktop/projects/sourceforge/gphoto2/missing --run autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
INSTALL_HEADER = $(INSTALL_DATA)
transform = s,x,x,
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
AA_CFLAGS = -I/usr/include
AA_LIBS = -L/usr/lib -Wl,-rpath,/usr/lib -laa -lm -L/usr/X11R6/lib -lX11 -lgpm -lslang
AMTAR = ${SHELL} /home/scottf/Desktop/projects/sourceforge/gphoto2/missing --run tar
AS = @AS@
AWK = mawk
BUILD_INCLUDED_LIBINTL = no
CATALOGS =  de.gmo
CATOBJEXT = .gmo
CC = gcc
CDK_LIBS = 
CFLAGS = -g -O2 -g -Wall -Wmissing-declarations -Wmissing-prototypes -I/home/scottf/Desktop/projects/sourceforge/gphoto2 -I/home/scottf/Desktop/projects/sourceforge/gphoto2/libgphoto2_port/libgphoto2_port
CPP = gcc -E
DATADIRNAME = share
DEPDIR = .deps
DLLTOOL = @DLLTOOL@
DOC_DIR = ${prefix}/share/doc/gphoto-2.0beta3
ECHO = echo
EXEEXT = 
GENCAT = gencat
GLIBC21 = yes
GMOFILES =  de.gmo
GMSGFMT = /usr/bin/msgfmt
GTKDOC = false
HAVE_GTK_DOC = 
HTML_DIR = ${prefix}/share/doc/gphoto-2.0beta3/html
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
INSTOBJEXT = .mo
INTLBISON = bison
INTLLIBS = 
INTLOBJS = 
INTL_LIBTOOL_SUFFIX_PREFIX = 
JPEG_LIBS = -ljpeg
LIBGPHOTO2_INCLUDEDIR = -I${includedir}
LIBGPHOTO2_LIBDIR = -L${libdir}
LIBGPHOTO2_LIBS = -lgphoto2 -lm
LIBGPHOTO2_PORT_DIR = libgphoto2_port
LIBGPHOTO2_VERSION = 2.0beta3
LIBICONV = 
LIBS = -ldl  -L/home/scottf/Desktop/projects/sourceforge/gphoto2/libgphoto2_port/libgphoto2_port/ -lgphoto2_port
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
MAINT = #
MKINSTALLDIRS = ./mkinstalldirs
MSGFMT = /usr/bin/msgfmt
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = gphoto
POFILES =  de.po
POSUB = po
RANLIB = ranlib
STRIP = strip
SUBDIRS_CAMLIBS =  agfa barbie canon casio digita dimera directory jamcam jd11 kodak konica minolta panasonic polaroid ptp samsung sierra stv0680 sonydscf1 sonydscf55
USE_INCLUDED_LIBINTL = no
USE_NLS = yes
VERSION = 2.0beta3
am__include = include
am__quote = 
dotlibs = 
install_sh = /home/scottf/Desktop/projects/sourceforge/gphoto2/install-sh

camlibdir = $(prefix)/lib/gphoto2
camlib_LTLIBRARIES = libgphoto2_ptp.la

INCLUDES = -I$(top_srcdir)/libgphoto2

libgphoto2_ptp_la_SOURCES = ptp.c ptp.h ptperr.h library.c

libgphoto2_ptp_la_LDFLAGS = \
 -module -avoid-version\
 -L$(shell pwd)/$(top_builddir)/libgphoto2/


libgphoto2_ptp_la_LIBADD = -lgphoto2
subdir = camlibs/ptp
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = $(top_builddir)/libgphoto2/config.h
CONFIG_CLEAN_FILES =
LTLIBRARIES = $(camlib_LTLIBRARIES)

libgphoto2_ptp_la_DEPENDENCIES =
am_libgphoto2_ptp_la_OBJECTS = ptp.lo library.lo
libgphoto2_ptp_la_OBJECTS = $(am_libgphoto2_ptp_la_OBJECTS)

DEFS = -DHAVE_CONFIG_H
DEFAULT_INCLUDES =  -I. -I$(srcdir) -I$(top_builddir)/libgphoto2
CPPFLAGS = 
LDFLAGS =  -g -Wall
LIBS = -ldl  -L/home/scottf/Desktop/projects/sourceforge/gphoto2/libgphoto2_port/libgphoto2_port/ -lgphoto2_port
depcomp = $(SHELL) $(top_srcdir)/depcomp
#DEP_FILES = $(DEPDIR)/library.Plo $(DEPDIR)/ptp.Plo
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) \
	$(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
DIST_SOURCES = $(libgphoto2_ptp_la_SOURCES)
DIST_COMMON = README Makefile.am Makefile.in
SOURCES = $(libgphoto2_ptp_la_SOURCES)

all: all-am

.SUFFIXES:
.SUFFIXES: .c .lo .o .obj

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool
$(srcdir)/Makefile.in: # Makefile.am  $(top_srcdir)/configure.in $(ACLOCAL_M4)
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  camlibs/ptp/Makefile
Makefile: # $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) && \
	  CONFIG_HEADERS= CONFIG_LINKS= \
	  CONFIG_FILES=$(subdir)/$@ $(SHELL) ./config.status
install-camlibLTLIBRARIES: $(camlib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(camlibdir)
	@list='$(camlib_LTLIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo " $(LIBTOOL) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$p $(DESTDIR)$(camlibdir)/$$p"; \
	    $(LIBTOOL) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$p $(DESTDIR)$(camlibdir)/$$p; \
	  else :; fi; \
	done

uninstall-camlibLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(camlib_LTLIBRARIES)'; for p in $$list; do \
	  echo " $(LIBTOOL) --mode=uninstall rm -f $(DESTDIR)$(camlibdir)/$$p"; \
	  $(LIBTOOL) --mode=uninstall rm -f $(DESTDIR)$(camlibdir)/$$p; \
	done

clean-camlibLTLIBRARIES:
	-test -z "$(camlib_LTLIBRARIES)" || rm -f $(camlib_LTLIBRARIES)
libgphoto2_ptp.la: $(libgphoto2_ptp_la_OBJECTS) $(libgphoto2_ptp_la_DEPENDENCIES) 
	$(LINK) -rpath $(camlibdir) $(libgphoto2_ptp_la_LDFLAGS) $(libgphoto2_ptp_la_OBJECTS) $(libgphoto2_ptp_la_LIBADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT) core *.core

distclean-compile:
	-rm -f *.tab.c

#include $(DEPDIR)/library.Plo
#include $(DEPDIR)/ptp.Plo

distclean-depend:
	-rm -rf $(DEPDIR)

.c.o:
#	source='$<' object='$@' libtool=no 
#	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' 
#	$(CCDEPMODE) $(depcomp) 
	$(COMPILE) -c `test -f $< || echo '$(srcdir)/'`$<

.c.obj:
#	source='$<' object='$@' libtool=no 
#	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' 
#	$(CCDEPMODE) $(depcomp) 
	$(COMPILE) -c `cygpath -w $<`

.c.lo:
#	source='$<' object='$@' libtool=yes 
#	depfile='$(DEPDIR)/$*.Plo' tmpdepfile='$(DEPDIR)/$*.TPlo' 
#	$(CCDEPMODE) $(depcomp) 
	$(LTCOMPILE) -c -o $@ `test -f $< || echo '$(srcdir)/'`$<
CCDEPMODE = depmode=none
uninstall-info-am:

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || etags $(ETAGS_ARGS) $$tags  $$unique $(LISP)

GTAGS:
	here=`CDPATH=: && cd $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH

DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)

top_distdir = ../..
distdir = $(top_distdir)/$(PACKAGE)-$(VERSION)

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  if test -f $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    $(mkinstalldirs) "$(distdir)/$$dir"; \
	  fi; \
	  if test -d $$d/$$file; then \
	    cp -pR $$d/$$file $(distdir) \
	    || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(LTLIBRARIES)

installdirs:
	$(mkinstalldirs) $(DESTDIR)$(camlibdir)

install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES) stamp-h stamp-h[0-9]*

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-camlibLTLIBRARIES clean-generic clean-libtool \
	mostlyclean-am

distclean: distclean-am

distclean-am: clean-am distclean-compile distclean-depend \
	distclean-generic distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

info: info-am

info-am:

install-data-am: install-camlibLTLIBRARIES

install-exec-am:

install-info: install-info-am

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-am

maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

uninstall-am: uninstall-camlibLTLIBRARIES uninstall-info-am

.PHONY: GTAGS all all-am check check-am clean clean-camlibLTLIBRARIES \
	clean-generic clean-libtool distclean distclean-compile \
	distclean-depend distclean-generic distclean-libtool \
	distclean-tags distdir dvi dvi-am info info-am install \
	install-am install-camlibLTLIBRARIES install-data \
	install-data-am install-exec install-exec-am install-info \
	install-info-am install-man install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool tags uninstall \
	uninstall-am uninstall-camlibLTLIBRARIES uninstall-info-am

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
