
static struct {
	short n;
	const char *txt;
} ptp_errors[] = {
	{PTP_RC_Undefined, "PTP Udefined Error"},
	{PTP_RC_OK, "PTP OK!"},
	{PTP_RC_GeneralError, "PTP General Error"},
	{PTP_RC_SessionNotOpen, "PTP Session Not Open"},
	{PTP_RC_InvalidTransactionID, "PTP Invalid Transaction ID"},
	{PTP_RC_OperationNotSupported, "PTP Operation Not Supportsd"},
	{PTP_RC_ParameterNotSupported, "PTP Parameter Not Supported"},
	{PTP_RC_IncompleteTransfer, "PTP Incomplete Transfer"},
	{PTP_RC_InvalidStorageId, "PTP Invalid Storage ID"},
	{PTP_RC_InvalidObjectHandle, "PTP Invalid Object Handle"},
	{PTP_RC_DevicePropNotSupported, "PTP Device Prop Not Supported"},
	{PTP_RC_InvalidObjectFormatCode, "PTP Invalid Object Format Code"},
	{PTP_RC_StoreFull, "PTP Store Full"},
	{PTP_RC_ObjectWriteProtected, "PTP Object Write Protected"},
	{PTP_RC_StoreReadOnly, "PTP Store Read Only"},
	{PTP_RC_AccessDenied, "PTP Access Denied"},
	{PTP_RC_NoThumbnailPresent, "PTP No Thumbnail Present"},
	{PTP_RC_SelfTestFailed, "PTP Self Test Failed"},
	{PTP_RC_PartialDeletion, "PTP Partial Deletion"},
	{PTP_RC_StoreNotAvailable, "PTP Store Not Available"},
	{PTP_RC_SpecyficationByFormatUnsupported,
	"PTP Specyfication By Format Unsupported"},
	{PTP_RC_NoValidObjectInfo, "PTP No Valid Object Info"},
	{PTP_RC_InvalidCodeFormat, "PTP Invalid Code Format"},
	{PTP_RC_UnknownVendorCode, "PTP Unknown Vendor Code"},
	{PTP_RC_CaptureAlreadyTerminated,
	"PTP Capture Already Terminated"},
	{PTP_RC_DeviceBusy, "PTP Device Bus"},
	{PTP_RC_InvalidParentObject, "PTP Invalid Parent Object"},
	{PTP_RC_InvalidDevicePropFormat, "PTP Invalid Device Prop Format"},
	{PTP_RC_InvalidDevicePropValue, "PTP Invalid Device Prop Value"},
	{PTP_RC_InvalidParameter, "PTP Invalid Parameter"},
	{PTP_RC_SessionAlreadyOpened, "PTP Session Already Opened"},
	{PTP_RC_TransactionCanceled, "PTP TransactionCanceled"},
	{PTP_RC_SpecificationOfDestinationUnsupported,
	"PTP Specification Of Destination Unsupported"},

	{PTP_ERROR_DATA_EXPECTED, "PTP Protocol error, data expected"},
	{PTP_ERROR_RESP_EXPECTED, "PTP Protocol error, response expected"},
};

