BASEPATH=..\..\..

all: start \
  dll \
  end

!include $(BASEPATH)\os2mak.inc

dll: $(CAMLIBS)\gpdc120.dll

library.o : library.c
   $(CC) -o $@ library.c $(CCFLAGS)

dc120.o : dc120.c
   $(CC) -o $@ dc120.c $(CCFLAGS)

kodak.def: dc120.o
   copy kodak.df kodak.def
   emxexp $** >> kodak.def

$(CAMLIBS)\gpdc120.dll: kodak.def library.o dc120.o
   $(LINK) $(DLLLINKFLAGS) -o $@ $** $(LIBS)
