/* Automatically generated by po2tbl.sed from project5.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"gphoto2 - Prototype", 2},
  {"_File", 3},
  {"E_xit", 4},
  {"Edit", 5},
  {"Select", 6},
  {"Camera", 7},
  {"Select Camera", 8},
  {"Export", 9},
  {"HTML Export", 10},
  {"button2", 11},
  {"button4", 12},
  {"button5", 13},
  {"gphoto2 - Image Window", 14},
  {"_Close", 15},
  {"button25", 16},
  {"button26", 17},
  {"button27", 18},
  {"button28", 19},
  {"button29", 20},
  {"button30", 21},
  {"button31", 22},
  {"button32", 23},
  {"button33", 24},
  {"image name", 25},
  {"gphoto2 - Gallery Export", 26},
  {"button41", 27},
  {"button42", 28},
  {"button43", 29},
  {"Gallery Name", 30},
  {"Available Images", 31},
  {"Gallery Images", 32},
  {"Add", 33},
  {"Add selected image to gallery", 34},
  {"Remove", 35},
  {"Remove selected image from gallery", 36},
  {"Up", 37},
  {"Move selected image location up", 38},
  {"Down", 39},
  {"Move selected image location down", 40},
  {"Image Preview", 41},
  {"Image Caption", 42},
  {"Select Gallery Theme", 43},
  {"Done", 44},
  {"Create Gallery", 45},
  {"Couldn't find pixmap file: %s", 46},
  {"Error loading pixmap file: %s", 47},
};

int _msg_tbl_length = 47;
