CCFLAGS=-O2 -c -I.. -I..\..\libgphoto2_port\include -I..\..\include -Zmtd -Zcrtdll -Zbin-files -D__ST_MT_ERRNO_ -I. -DOS2 -DHAVE_TERMIOS_H
CC=gcc

all: start \
  lib \
  end

start:
  @echo ****
  @echo   Entering:      $(MAKEDIR)
  @echo   using CCFLAGS: $(CCFLAGS)
  @echo ****

end:
  @echo ****
  @echo   Done: $(MAKEDIR)
  @echo ****

lib: ..\..\obj\script.o

..\..\obj\script.o: script.c
  @$(CC) -o $@ $** $(CCFLAGS)
