name: "Matrix-Test"

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  ix-build:
    name: "${{ matrix.os }} ix-build"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] # , macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: 'Determine number of cores to build on (Linux)'
        if: runner.os == 'Linux'
        run: echo NPROC="$(nproc)" >> $GITHUB_ENV

      - name: 'Determine number of cores to build on (macOS)'
        if: runner.os == 'macOS'
        run: echo NPROC="$(sysctl -n hw.logicalcpu)" >> $GITHUB_ENV

      - name: 'Check shell environment'
        run: |
          echo "NPROC=$NPROC"
          echo "SHELL=$SHELL"
          echo "BASH_VERSION=$BASH_VERSION"
          $SHELL --version

  msys2-build:
    needs: ix-build

    name: '${{ matrix.os }} ${{ matrix.sys }} msys2-build'
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        include:
          - sys: mingw32
            env: i686
          - sys: mingw64
            env: x86_64
          - sys: ucrt64
            env: ucrt-x86_64
          - sys: clang64
            env: clang-x86_64

    defaults:
      run:
        shell: 'msys2 {0}'

    steps:
      - name: 'git config core.autocrlf (Windows)'
        run: git config --global core.autocrlf input
        shell: bash

      - uses: actions/checkout@v3

      - name: 'Set MINGW_ARCH (Windows)'
        shell: bash
        run: echo MINGW_ARCH="${{ matrix.sys }}" >> $GITHUB_ENV

      - name: 'Set up MSYS2 and Install Software'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.sys }}

      - name: 'Determine number of cores to build on (Windows)'
        run: echo NPROC="${NUMBER_OF_PROCESSORS-unknown}" >> $GITHUB_ENV

      - name: 'Check shell environment'
        run: |
          echo "NPROC=$NPROC"
          echo "SHELL=$SHELL"
          echo "BASH_VERSION=$BASH_VERSION"
          $SHELL --version
