name: "Matrix-Test"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    name: "${{ matrix.os }} ${{ matrix.sys }} build"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest }
          - { os: macos-latest }
          - { os: windows-latest, sys: mingw32 }
          - { os: windows-latest, sys: mingw64 }

    env:
      MINGW_ARCH: ${{ matrix.sys }}

    defaults:
      if: runner.os == 'Windows'
      run:
        shell: msys2 {0}

    steps:
      - name: 'git config'
        if: runner.os == 'Windows'
        run: git config --global core.autocrlf input
        shell: bash

      - uses: actions/checkout@v3

      - name: 'Set up MSYS2 and Install Software'
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.sys }}

      - name: 'Determine number of cores to build on (Linux)'
        if: runner.os == 'Linux'
        run: echo NPROC="$(nproc)" >> $GITHUB_ENV

      - name: 'Determine number of cores to build on (Windows)'
        if: runner.os == 'Windows'
        run: echo NPROC="${NUMBER_OF_PROCESSORS-unknown}" >> $GITHUB_ENV

      - name: 'Determine number of cores to build on (macOS)'
        if: runner.os == 'macOS'
        run: echo NPROC="$(sysctl -n hw.logicalcpu)" >> $GITHUB_ENV

      - name: 'Check NPROC value'
        run: echo NPROC=$NPROC
